### ISSUE TITLE
[FEATURE REQUEST] Add manual `connect_notify_local` method to glib::SignalGroup

### ISSUE THREAD

**Issue by melix99** [gtk-rs/gtk-rs-core#1021]
Currently to listen to notify signals of the properties of the target object of a `glib::SignalGroup`, we are forced to use the regular `connect_local`, which is a bit annoying. It would be cool to have a `connect_notify_local` to make things simpler to use.

**Comment by melix99** [comment]
More info here: https://github.com/melix99/telegrand/pull/462#discussion_r1108776250

**Comment by sdroege** [comment]
Do you want to provide a PR for this?
