### ISSUE TITLE
Support PathBuf in Properties macro

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs-core#1029]
The required traits are not implemented for PathBuf and they would have to map to a String internally.

**Comment by pbor** [comment]
Rust's PathBuf or the new glib one?

Also, I guess it would not hurt, but is it really useful? My understanding is that both are meant to be used when constructing one, but then you probably want to stora `Path` or `GFile` in the property

**Comment by sdroege** [comment]
The Rust `PathBuf`. It's the owned equivalent to `&Path`, just like `String` is to `&str`, so it's the one you would want to store.

**Comment by sdroege** [comment]
Related to this, also https://github.com/gtk-rs/gtk-rs-core/issues/1030

**Comment by ranfdev** [comment]
PathBuf is not a String, so I'm not 100% convinced that's the correct behavior.

PathBuf is an `OsString` and that doesn't implement `ToValue`.

If we implement `HasParamSpec` for `PathBuf`, we should also do that for `OsString`.

**Comment by sdroege** [comment]
We're implementing the other Value traits for `PathBuf` / `Path` IIRC, so that would make sense
