### ISSUE TITLE
Move to workspace dependencies for common / git dependencies

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#1072]
That way we only have to update them in a single place when doing releases, for example, and versions are guaranteed to stay in sync.

@bilelmoussaoui What do you think?

**Comment by bilelmoussaoui** [comment]
I wasn't aware we can have workspace dependencies...I wonder how those works when publishing the crate on crates.io?

**Comment by sdroege** [comment]
Just like now. `cargo publish` is not directly uploading our `Cargo.toml`s but is modifying them before uploading, see e.g. https://docs.rs/crate/glib/latest/source/ `Cargo.toml` vs `Cargo.toml.orig`

**Comment by bilelmoussaoui** [comment]
This is now done, still needs improvements for the ffi crates but could be done at a later stage.
