### ISSUE TITLE
property macro: Support construct_only

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk-rs-core#1088]
I have a bunch of

```rust
#[property(get, set, builder().construct_only())]
```

in my code. I don't really need the setter since it will always fail and the `builder().` doesn't look to too pretty. Would it be possible to have something like the following?

```rust
#[property(get, construct_only)]
```

**Comment by bilelmoussaoui** [comment]
At least per https://github.com/gtk-rs/gtk-rs-core/blob/master/glib-macros/src/properties.rs#L537-L538, the setter should not be generated if you use `#[property(get, set, construct_only)]`
