### ISSUE TITLE
docs no longer display the required features

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs-core#1090]
See https://gtk-rs.org/gtk4-rs/git/docs/gtk4/subclass/symbolic_paintable/index.html and https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/subclass/symbolic_paintable/index.html

cc @AaronErhardt

**Comment by AaronErhardt** [comment]
I'll look into it.

**Comment by bilelmoussaoui** [comment]
thanks for the quick fix @AaronErhardt
