### ISSUE TITLE
Seal Ext / ImplExt traits

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs-core#1093]
We should look at which traits must be sealed other then the ones mentioned in the issue title.

**Comment by jf2048** [comment]
Here is a list of glib traits that are not sealed and not implemented by any macro:

- :seal: `Cast`
- :seal: `CastNone`
- `FromGlibContainer`
- `FromGlibPtrContainer`
- :seal: `InterfaceList`
- :seal: `IntoClosureReturnValue`
- `IntoGStr`
- `IntoOptionalGStr`
- `IntoPtrSlice`
- `IntoStrV`
- :seal: `IsSubclassableDefault`
- :seal: `MayDowncastTo`
- `OptionIntoGlib`
- :seal: `PrerequisiteList`
- `Property`
- `PropertyGet`
- `PropertySet`
- `PropertySetNested`
- :seal: `Ptr`
- :seal: `ToSendValue`
- :seal: `TryFromClosureReturnValue`
- :seal: `Watchable`

I put :seal: next to the ones I think should probably be sealed

**Comment by jf2048** [comment]
Seems simple enough for gtk3: https://github.com/gtk-rs/gtk3-rs/pull/821

Now to add it to gir?

**Comment by sdroege** [comment]
Sealing approach from that PR looks good to me. I'll look at the list of traits above next week :)

**Comment by bilelmoussaoui** [comment]
Does docs embedding works fine for those sealed traits?

**Comment by jf2048** [comment]
Seems to work here

**Comment by bilelmoussaoui** [comment]
This is now done
