### ISSUE TITLE
[FEATURE REQUEST] Update rust version

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk-rs-core#1097]
In the matrix chat we talked about doing it, to keep the same min version as gstreamer-rs (rust 1.66, see here https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/blob/main/gstreamer-app/Cargo.toml)

**Comment by sdroege** [comment]
What did we discuss exactly, why did we want to do this? :)
