### ISSUE TITLE
[BUG] Build error when using derive property with a custom enum in a GObject

### ISSUE THREAD

**Issue by gwen-lg** [gtk-rs/gtk-rs-core#1108]
**Bug description**

When I tried to use a custom enum as property in a GObject with 'Property' derive I got the error :

> error[E0061]: this function takes 2 arguments but 1 argument was supplied
>   --> src/main.rs:25:3
>    |
> 22 |     #[derive(Properties, Default)]
>    |              ---------- an argument of type `MyEnum` is missing
> ...
> 25 |         #[property(get, set)]
>    |         ^
>    |
> help: provide the argument
>    |
> 22 |     #[derive(#(enum_value, /* MyEnum */), Default)]
>    |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Expand**

After investigation, I found than the expand of properties() call an implementation of param_spec_builder() with only name, but the generated implementation for Enum also want a default_value :

```
fn properties() -> &'static [ParamSpec] {
            use glib::once_cell::sync::Lazy;
            static PROPERTIES: Lazy<[glib::ParamSpec; 1usize]> = Lazy::new(|| [
                <<RefCell<
                    MyEnum,
                > as glib::Property>::Value as glib::HasParamSpec>::param_spec_builder()(
                        "enum-value",
                    )
                    .readwrite()
                    .build(),
            ]);
            PROPERTIES.as_ref()
		}
```

```
impl glib::HasParamSpec for MyEnum {
    type ParamSpec = glib::ParamSpecEnum;
    type SetValue = Self;
    type BuilderFn = fn(
        &::core::primitive::str,
        Self,
    ) -> glib::ParamSpecEnumBuilder<Self>;
    fn param_spec_builder() -> Self::BuilderFn {
        |name, default_value| Self::ParamSpec::builder_with_default(name, default_value)
    }
}
```

A test project can be found here : https://github.com/gwen-lg/gtk_enum_property

**Comment by gwen-lg** [comment]
I supposed than like the enum has a default value specified, a good fix should be than the param_spec_builder implementation shouldn't ask to specified a default value.

I could be interested to make the fix, but I would like to be guided to know where to look.

**Comment by ranfdev** [comment]
Sadly, every property needs a default value specified in the related ParamSpec. The Rust type system doesn't support specialization, so we can't automatically put a default value for Enums implementing Default and request a value from the user when the Default trait isn't implemented.

Therefore the user must always specify a default value for the enum manually.

**Comment by gwen-lg** [comment]
Ok, so how I can specify a default value for property ?
I tried :
```
    pub struct MyObject {
		#[property(get, set, default_value = MyEnum::Value1)]
		pub enum_value: RefCell<MyEnum>,
    }
```
But without success :( 
What is missing in my example : 
https://github.com/gwen-lg/gtk_enum_property/blob/main/src/main.rs ?

**Comment by ranfdev** [comment]
Try with `#[property(get, set, builder(MyEnum:Value1)]`

With that syntax, the macro is going to pass the argument of `builder(...)` to `ParamSpecEnum::builder_with_default`.

**Comment by gwen-lg** [comment]
It's build now, thank you :+1: 

There is a documentation on derive options ?
I haven't found it.

**Comment by ranfdev** [comment]
> There is a documentation on derive options ?
> I haven't found it.

No worries...

https://gtk-rs.org/gtk-rs-core/stable/latest/docs/glib/derive.Properties.html

**Comment by gwen-lg** [comment]
Oh, I had seen this page, but before understanding the problem.
The error message is little cryptic ^^

Do you think it's possible to detect the error at macro expand time, and return a better error message ?
