### ISSUE TITLE
glib build fail for arm

### ISSUE THREAD

**Issue by mukunth1987** [gtk-rs/gtk-rs-core#1121]
Hello,
   I tried to include glib in Cargo.toml for x86 and build is fine. I am able to call gmainloop api's and its working like charm.

But when I try to build for arm, build errors pop up and quite stuck unable to proceed further.

**Build cmd :**
```
cargo build --target=armv7-unknown-linux-gnueabi --config target.armv7-unknown-linux-gnueabi.linker=\"arm-linux-gnueabi-gcc\"
```

**Cargo.toml**
```
[dependencies]
glib = { git = "https://github.com/gtk-rs/gtk-rs-core.git", package = "glib" }
```

Below is the error log
```
error: could not find system library 'gobject-2.0' required by the 'gobject-sys' crate

--- stderr
error: failed to run custom build command for 'gobject-sys v0.18.0 (https://github.com/gtk-rs/gtk-rs-core.git#ce523803)

Package libpcre was not found in pkg-config search path
Perhaps you should add the directory containing 'libpcre.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpcre', required by 'glib-2.0', not found.

Any help on the issue ?
```

**Comment by sdroege** [comment]
Your build environment is broken and/or incomplete. You seem to have GLib available for your target platform, but not pcre (which is a dependency of GLib).

Please report this to wherever you got your GLib build from, thanks!
