### ISSUE TITLE
[BUG] Panic in gio input stream

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk-rs-core#1139]
While fetching `gemini://gemini.tuxmachines.org//n/2023/07/22/today_s_howtos.gmi`, using a `gio::SocketClient` with Tls on.

```
(geopard:2): GLib-GIO-DEBUG: 23:44:28.090: GSocketClient: Starting new address enumeration
(geopard:2): GLib-GIO-DEBUG: 23:44:28.095: IPv6 DNS error: Error resolving “gemini.tuxmachines.org”: No address associated with hostname
(geopard:2): GLib-GIO-DEBUG: 23:44:28.095: GSocketClient: Address enumeration succeeded
(geopard:2): GLib-GIO-DEBUG: 23:44:28.095: GSocketClient: Starting TCP connection attempt
(geopard:2): GLib-GIO-DEBUG: 23:44:28.313: GSocketClient: TCP connection successful
(geopard:2): GLib-GIO-DEBUG: 23:44:28.313: GSocketClient: Starting application layer connection
(geopard:2): GLib-GIO-DEBUG: 23:44:28.313: GSocketClient: Starting TLS handshake
(geopard:2): GLib-GIO-DEBUG: 23:44:28.528: GSocketClient: TLS handshake succeeded
(geopard:2): GLib-GIO-DEBUG: 23:44:28.528: GSocketClient: Connection successful!
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', [...]/_build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/gio-0.17.4/src/input_stream.rs:502:69
```

In the repo, this is the failing line
https://github.com/gtk-rs/gtk-rs-core/blob/85d23fc8f8428e863d859b3c686d4ed3775b4004/gio/src/input_stream.rs#L453

**Comment by bilelmoussaoui** [comment]
Interesting, can you check what is the error kind?

**Comment by ranfdev** [comment]
The error is not an `IOErrorEnum` but a
```
&err = Error {
    domain: g-tls-error-quark,
    code: 6,
    message: "TLS connection closed unexpectedly",
}
```

I guess I can try mapping every error type to an `IOErrorEnum` and call it a day.
Other libraries like tokio will prevent you from using a stream if you plan on emitting error types different than `std::io::Error`. (example: `LineStream`, https://docs.rs/tokio-stream/0.1.14/tokio_stream/wrappers/struct.LinesStream.html#impl-Stream-for-LinesStream%3CR%3E)

But here the error are more dynamics, so we have to convert them once we receive them.
