### ISSUE TITLE
Replace once_cell with std

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs-core#1141]
Currently, despite requiring 1.70, we are still depending on once_cell. It would be nice to completely remove that dependency and replace it with std where possible.

**Comment by AbuShawarib** [comment]
How would you replace `once_cell::sync::Lazy`? `std::sync::LazyLock` and `std::cell::LazyCell` are still unstable.

**Comment by A6GibKm** [comment]
You could just use OnceCell for them, is just slightly less comfortable to use. Having said that, I would just wait till they are stabilized to reduce the work needed.
