### ISSUE TITLE
[HELP]SourceId as field in Class

### ISSUE THREAD

**Issue by harshakhmk** [gtk-rs/gtk-rs-core#1164]
Hi, I am using Glib crate to add and remove events from eventloop, when adding an event, it returns sourceId which I need to store it in a class and use the variable to remove event, but the class is implementing Clone and sourceId isn't, any suggestions on how to store it 

Sample code:
```
#[derive(Clone)]
struct Test{
id: u32,
source_id: SourceId,
}

fn addEvent() -> SourceId
{
    /* 
      Code to add an event to eventloop
     */ 
}

fn removeEvent(source_id: SourceId) 
{
     source_id.remove()
}
```

**Comment by bilelmoussaoui** [comment]
Wrap it in a Rc<>

**Comment by harshakhmk** [comment]
I tries to wrap source_id field in class as 
``` 
struct Test {
id : u32, 
source_id : Rc<SourceId>,
}

Impl Test{
pub fn new(ID :u32 ) -> Test
{
id : ID,
source_id: Rc::new(SourceId (1))),
}

```
Now I was getting error, " cannot initialize a tuple struct which contains private fields"

**Comment by bilelmoussaoui** [comment]
you cannot construct the type yourself.
