### ISSUE TITLE
ci: Run cargo-deny on the CI (regularly) and maintain a deny.toml

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#1178]
This will make sure that we don't have duplicate dependencies in different versions, only depend on crates with suitable licenses (i.e. non-copyleft OSI licenses here) and also don't depend on anything that ships with dubious binaries (hello serde-derive).

In gstreamer-rs / gst-plugins-rs I'm already using that since a few years and it's very useful.

I don't know what Github Actions offers here but I guess someone already wrote an extension or even bot (like dependabot) for this.

CC @bilelmoussaoui @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Sounds good to me!
