### ISSUE TITLE
Make cairo v1_16 and gdk-pixbuf v2_42 features the default

### ISSUE THREAD

**Issue by alatiera** [gtk-rs/gtk-rs-core#1184]
All the systems we want to support already have these, if not newer. Should allow us to delete some code and conditionals

We could also look at dropping a handful of older glib features as well, maybe everything before `v2_72`.

-[ ] For the gnome_45 feature we will also want to bump cairo to `v1_18`.

**Comment by alatiera** [comment]
We can also get rid of all the features before `pango/v1_50`

**Comment by sdroege** [comment]
The main question then is if it's worth it. Does it actually simplify anything, how much code can be removed?

**Comment by sdroege** [comment]
(every time we bump minimum versions, there are multiple users that are affected and it makes no sense to bump the minimum versions if there's not really much of an advantage)

**Comment by bilelmoussaoui** [comment]
I also don't agree with this, it is not worth it.

**Comment by alatiera** [comment]
Yea it's a bit weird, cause a lot of these versions are just not supported and buggy, like cairo, but also it's not like distros will ever upgrade.
