### ISSUE TITLE
`toml_edit` using multiple versions with `gtk` 0.18

### ISSUE THREAD

**Issue by dklassic** [gtk-rs/gtk-rs-core#1206]
Currently `gtk` 0.18 uses both 0.19 and 0.20 versions of `toml_edit` due to dependency of:

- `toml_edit` v0.19.15 <- `proc-macro-crate` v1.3.1 <- `glib-macros` v0.18.2 <- `glib` v0.18.2 <- `atk` v0.18.0 <- `gtk` v0.18.1
- `toml_edit` v0.20.2 <- `toml` v0.8.2 <- `system-deps` v6.1.2 <- `atk-sys` v0.18.0 <- `atk` v0.18.0 <- `gtk` v0.18.1

`proc-macro-crate` has since released [v2](https://github.com/bkchr/proc-macro-crate/releases/tag/v2.0.0) two weeks ago which uses `toml_edit` 0.20 that'll solve this issue.

**Comment by bilelmoussaoui** [comment]
This was already resolved in https://github.com/gtk-rs/gtk-rs-core/pull/1198 and would be fixed in the next release
