### ISSUE TITLE
Consider removing channels from glib

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gtk-rs-core#1213]
As mentioned by @sdroege in https://github.com/gtk-rs/gtk4-rs/pull/1521#issuecomment-1774071454:

>Should we maybe remove the GLib channel? It mostly exists from the times before async was mature and because people instead used timeout callbacks to periodically check if a non-async channel contains something.

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/1216

**Comment by p-kraszewski** [comment]
Splendid move! Could you consider using Rust's [deprecated](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-deprecated-attribute) attribute _next time_, let's say, for 2 releases?

**Comment by bilelmoussaoui** [comment]
It was deprecated during the release cycle of 0.18.x.

**Comment by p-kraszewski** [comment]
Ok. My bad. 

* First note on deprecation (merged into 0.18.4): 2023.11.25  93f6a02a32d6e2a532cdb3a8922dbb9b31419a93
* Feature reaped (merged into 0.19 line): 2023.11.31 2cb10ec3f305f954ca30c708c752458e4af4eabb

**Comment by sdroege** [comment]
First release without the API was on Sunday, so that gives a bit more than 2 months.
