### ISSUE TITLE
[FEATURE REQUEST] Property macro: Don't create field for underscore prefixed properties

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk-rs-core#1235]
Sometimes there are properties that are derived from other values and not from the value of a field. In those cases, it doesn't make sense to create a struct field and it's also not always possible to define the type via the field since it might not implement `Default`

My current code

```rust
        #[property(override_interface = gtk::Scrollable, type = gtk::ScrollablePolicy, get = Self::scroll_policy, set = Self::set_ignore_scroll_policy)]
        pub(super) _hscroll_policy: (),
```

This would be more convenient but doesn't work since `gtk::Scrollable` does not implement `Default`

```rust
        #[property(override_interface = gtk::Scrollable, get = Self::scroll_policy, set = Self::set_ignore_scroll_policy)]
        pub(super) _hscroll_policy: gtk::Scrollable,
```

So maybe it's worth considering to not add the fields that are `_` prefixed?

**Comment by ranfdev** [comment]
The Properties macro is a derive macro, so it can only derive/generate additional code, without altering the struct definition itself.

Any field defined in the struct is kept as is. 
We cannot remove any field from the struct definition.

To define a field without any owned value you can use the type `()`, as you already did, or `PhantomData<glib::Scrollable>`. With `PhantomData` you can skip the `type = glib::ScrollablePolicy` attribute
