### ISSUE TITLE
[BUG] 128 message limit when using tokio channels with `spawn_future_local`

### ISSUE THREAD

**Issue by JakeStanger** [gtk-rs/gtk-rs-core#1251]
## Bug description

When using Tokio's MPSC channels with GTK/GLib and the new `spawn_future_local` method, there seems to be a strange issue where the first 128 messages are received and then the receiver just stops. No errors are returned (unless you try to force more into the channel from another task) and the receiver continues, but the channel fills up and hangs indefinitely.

Changing the channel buffer does not affect this 128 limit. Receiving via a Tokio task does not hit this limit, so this looks to be something peculiar with GLib futures.

## Min repoduction

Repo containing below can be found here:
https://github.com/JakeStanger/gtk-tokio-channel-repro

**cargo.toml**
```toml
[package]
name = "gtk-tokio-test"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.18.1"
glib = "0.18.4"
tokio = { version = "1.35.0", features = [ "full" ] }
````

**main.rs**
```rs
use std::time::Duration;
use gtk::prelude::*;
use tokio::sync::mpsc;
use tokio::time::sleep;

#[tokio::main]
async fn main() {
    let app = gtk::Application::builder().build();

    app.connect_activate(|app| {
        gtk::ApplicationWindow::new(app);

        let (tx, mut rx) = mpsc::channel(4);

        tokio::spawn(async move {
            let mut i = 0;
            loop {
                tx.send(i).await.unwrap();
                println!("SEND [{i}] {}/{}", tx.capacity(), tx.max_capacity()); // prints 0-131 (until channel full)
                sleep(Duration::from_millis(100)).await;

                i += 1;
            }
        });

        glib::spawn_future_local(async move {
            while let Some(i) = rx.recv().await {
                println!("RECV [{i}]"); // prints 0-127 ALWAYS
            }

            println!("RECV END"); // never prints
        });
    });

    app.run();
}
```

## Output

<details>
<summary>stdout</summary>

```
/sbin/cargo run --color=always --package gtk-tokio-test --bin gtk-tokio-test
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/gtk-tokio-test`
SEND [0] 3/4
RECV [0]
SEND [1] 3/4
RECV [1]
SEND [2] 3/4
RECV [2]
SEND [3] 3/4
RECV [3]
SEND [4] 3/4
RECV [4]
SEND [5] 3/4
RECV [5]
SEND [6] 3/4
RECV [6]
SEND [7] 3/4
RECV [7]
SEND [8] 3/4
RECV [8]
SEND [9] 3/4
RECV [9]
SEND [10] 3/4
RECV [10]
SEND [11] 3/4
RECV [11]
SEND [12] 3/4
RECV [12]
SEND [13] 3/4
RECV [13]
SEND [14] 3/4
RECV [14]
SEND [15] 3/4
RECV [15]
SEND [16] 3/4
RECV [16]
SEND [17] 3/4
RECV [17]
SEND [18] 3/4
RECV [18]
SEND [19] 3/4
RECV [19]
SEND [20] 3/4
RECV [20]
SEND [21] 3/4
RECV [21]
SEND [22] 3/4
RECV [22]
SEND [23] 3/4
RECV [23]
SEND [24] 3/4
RECV [24]
SEND [25] 3/4
RECV [25]
SEND [26] 3/4
RECV [26]
SEND [27] 3/4
RECV [27]
SEND [28] 3/4
RECV [28]
SEND [29] 3/4
RECV [29]
SEND [30] 3/4
RECV [30]
SEND [31] 3/4
RECV [31]
SEND [32] 3/4
RECV [32]
SEND [33] 3/4
RECV [33]
SEND [34] 3/4
RECV [34]
SEND [35] 3/4
RECV [35]
SEND [36] 3/4
RECV [36]
SEND [37] 3/4
RECV [37]
SEND [38] 3/4
RECV [38]
SEND [39] 3/4
RECV [39]
SEND [40] 3/4
RECV [40]
SEND [41] 3/4
RECV [41]
SEND [42] 3/4
RECV [42]
SEND [43] 3/4
RECV [43]
SEND [44] 3/4
RECV [44]
SEND [45] 3/4
RECV [45]
SEND [46] 3/4
RECV [46]
SEND [47] 3/4
RECV [47]
SEND [48] 3/4
RECV [48]
SEND [49] 3/4
RECV [49]
SEND [50] 3/4
RECV [50]
SEND [51] 3/4
RECV [51]
SEND [52] 3/4
RECV [52]
SEND [53] 3/4
RECV [53]
SEND [54] 3/4
RECV [54]
SEND [55] 3/4
RECV [55]
SEND [56] 3/4
RECV [56]
SEND [57] 3/4
RECV [57]
SEND [58] 3/4
RECV [58]
SEND [59] 3/4
RECV [59]
SEND [60] 3/4
RECV [60]
SEND [61] 3/4
RECV [61]
SEND [62] 3/4
RECV [62]
SEND [63] 3/4
RECV [63]
SEND [64] 3/4
RECV [64]
SEND [65] 3/4
RECV [65]
SEND [66] 3/4
RECV [66]
SEND [67] 3/4
RECV [67]
SEND [68] 3/4
RECV [68]
SEND [69] 3/4
RECV [69]
SEND [70] 3/4
RECV [70]
SEND [71] 3/4
RECV [71]
SEND [72] 3/4
RECV [72]
SEND [73] 3/4
RECV [73]
SEND [74] 3/4
RECV [74]
SEND [75] 3/4
RECV [75]
SEND [76] 3/4
RECV [76]
SEND [77] 3/4
RECV [77]
SEND [78] 3/4
RECV [78]
SEND [79] 3/4
RECV [79]
SEND [80] 3/4
RECV [80]
SEND [81] 3/4
RECV [81]
SEND [82] 3/4
RECV [82]
SEND [83] 3/4
RECV [83]
SEND [84] 3/4
RECV [84]
SEND [85] 3/4
RECV [85]
SEND [86] 3/4
RECV [86]
SEND [87] 3/4
RECV [87]
SEND [88] 3/4
RECV [88]
SEND [89] 3/4
RECV [89]
SEND [90] 3/4
RECV [90]
SEND [91] 3/4
RECV [91]
SEND [92] 3/4
RECV [92]
SEND [93] 3/4
RECV [93]
SEND [94] 3/4
RECV [94]
SEND [95] 3/4
RECV [95]
SEND [96] 3/4
RECV [96]
SEND [97] 3/4
RECV [97]
SEND [98] 3/4
RECV [98]
SEND [99] 3/4
RECV [99]
SEND [100] 3/4
RECV [100]
SEND [101] 3/4
RECV [101]
SEND [102] 3/4
RECV [102]
SEND [103] 3/4
RECV [103]
SEND [104] 3/4
RECV [104]
SEND [105] 3/4
RECV [105]
SEND [106] 3/4
RECV [106]
SEND [107] 3/4
RECV [107]
SEND [108] 3/4
RECV [108]
SEND [109] 3/4
RECV [109]
SEND [110] 3/4
RECV [110]
SEND [111] 3/4
RECV [111]
SEND [112] 3/4
RECV [112]
SEND [113] 3/4
RECV [113]
SEND [114] 3/4
RECV [114]
SEND [115] 3/4
RECV [115]
SEND [116] 3/4
RECV [116]
SEND [117] 3/4
RECV [117]
SEND [118] 3/4
RECV [118]
SEND [119] 3/4
RECV [119]
SEND [120] 3/4
RECV [120]
SEND [121] 3/4
RECV [121]
SEND [122] 3/4
RECV [122]
SEND [123] 3/4
RECV [123]
SEND [124] 3/4
RECV [124]
SEND [125] 3/4
RECV [125]
SEND [126] 3/4
RECV [126]
SEND [127] 3/4
RECV [127]
SEND [128] 3/4
SEND [129] 2/4
SEND [130] 1/4
SEND [131] 0/4
^C
Process finished with exit code 130 (interrupted by signal 2:SIGINT)
```

</details>

**Comment by sdroege** [comment]
A simpler testcase is this btw:

```rust
use std::time::Duration;
use tokio::sync::mpsc;
use tokio::time::sleep;

fn main() {
    let rt = tokio::runtime::Runtime::new().unwrap();
    let ctx = glib::MainContext::default();
    let loop_ = glib::MainLoop::new(Some(&ctx), false);

    let (tx, mut rx) = mpsc::channel(4);

    rt.spawn(async move {
        let mut i = 0;
        loop {
            tx.send(i).await.unwrap();
            println!("SEND [{i}] {}/{}", tx.capacity(), tx.max_capacity()); // prints 0-131 (until channel full)
            sleep(Duration::from_millis(100)).await;

            i += 1;
        }
    });

    glib::spawn_future_local(async move {
        while let Some(i) = rx.recv().await {
            println!("RECV [{i}]"); // prints 0-127 ALWAYS
        }

        println!("RECV END"); // never prints
    });

    loop_.run();
}
```

However this runs forever for me, so maybe there's something specific to yours. I'll check in more detail tomorrow.

One thing you should never do is to use `#[tokio::main]` like this. You're going to block one of the runtime's threads with the GLib main loop (from `app.run()` in your case), which is a waste of resources at best and a source of strange bugs if you're unlucky. That most likely doesn't cause *this* problem though.

**Comment by sdroege** [comment]
I can reproduce it with your testcase FWIW.

**Comment by JakeStanger** [comment]
Thanks for confirming & for a working case. I have just done some quick testing with the differences between our cases and have found:

- Switching the GTK init out for the GLib init does NOT make a difference (makes sense, I assume GTK just calls these same methods to init the context under the hood).
- Manually creating the tokio runtime DOES fix the issue

> One thing you should never do is to use #[tokio::main] like this. You're going to block one of the runtime's threads with the GLib main loop (from app.run() in your case), which is a waste of resources at best and a source of strange bugs if you're unlucky.

Gotcha, appreciate the tip, and looks like the 'unlucky' case is being hit here potentially.

I assume the 'correct' approach here instead is to handle it as you have above, creating a runtime and hooking into that where necessary? I did notice the gtk-rs book had examples like that and wondered what the reasoning was.

**Comment by sdroege** [comment]
> I assume the 'correct' approach here instead is to handle it as you have above, creating a runtime and hooking into that where necessary?

Yes, `#[tokio::main]` is not doing much else (the body of `main` is just wrapped in that and a `runtime.block_on()` IIRC).

> I did notice the gtk-rs book had examples like that and wondered what the reasoning was.

Maybe that should be explained in the book then. Do you want to send a PR or create an issue for that at least? :)

**Comment by JakeStanger** [comment]
> (the body of main is just wrapped in that and a runtime.block_on() IIRC).

Have checked and that's indeed the case. From reading the Tokio docs that block_on call is almost certainly the problem, as it provides the top-level runtime context entry.

>  Do you want to send a PR or create an issue for that at least? :)

PR raised :) Thanks for your help, I think with that additional clarification that resolves the issue sufficiently for me at least.

Do you think it's feasible/worth it to add some kind of runtime protection (a log/panic/whatever) into gtk-rs to catch issues like this before they occur? I can't be the only one and it's tricky to track things like this down without knowing the oddities of both runtimes.

**Comment by sdroege** [comment]
Yeah I'm not sure why exactly this behaves like this, that would need more debugging time than I currently have available. My best guess would be that for some reason tokio tries to schedule the task on that one runtime thread that is blocked. But not sure why that would happen so reliably :)

**Comment by sdroege** [comment]
From a GLib bindings point of view I don't think there's anything we can easily do to detect this situation without also depending on tokio.

**Comment by awused** [comment]
Just happened to see this bug; for anyone still curious, the limit of 128 messages comes from tokio's [pseudo-preemption](https://tokio.rs/blog/2020-04-preemption). Whenever that comes up it's a sign that the runtime is being blocked.

**Comment by JakeStanger** [comment]
Thanks for linking, that's an interesting read & a good insight into what's going on under the hood to have caused this.
