### ISSUE TITLE
[BUG] Cannot create `ApplicationWindow`s inside `spawn_future_local`

### ISSUE THREAD

**Issue by JakeStanger** [gtk-rs/gtk-rs-core#1277]
**Bug description**

I have a scenario where I want to create application windows based on events external to GTK, received asynchronously, so am using the `spawn_future_local` method to create a future on the main thread in which the windows are created.

This seems to hit some strange behaviour however, as GTK throws a critical error at you:

```
(gtk-tokio-test:232637): Gtk-CRITICAL **: 23:12:22.991: New application windows must be added after the GApplication::startup signal has been emitted.
```

As you can see from the minimal repro below, the future is created inside the `activate` method so should always execute after the startup signal.

```rust
use glib::clone;
use gtk::ApplicationWindow;
use gtk::prelude::*;

fn main() {
    let app = gtk::Application::builder().build();

    app.connect_activate(move |app| {
        glib::spawn_future_local(clone!(@strong app => async move {
            ApplicationWindow::new(&app);
        }));
    });

    app.run();
}
```

It could be possible it is not actually the future, but rather related to cloning the `Application`, although that seems unlikely? To me this points to a strange quirk of the async runtime.

---

I am not currently aware of any workarounds, so if this is not fixable and anybody has a clue on how to approach this differently, that'd be appreciated.

**Comment by sdroege** [comment]
The problem here is that nothing is holding the application after startup returned, so the application just quits right afterwards and when the future is executed it's already in the middle of stopping.

This solves it, for example:

```rust
use glib::clone;
use gtk::prelude::*;
use gtk::ApplicationWindow;

fn main() {
    let app = gtk::Application::builder().build();

    app.connect_activate(move |app| {
        let hold = app.hold();
        glib::spawn_future_local(clone!(@strong app => async move {
            let _hold = hold;
            ApplicationWindow::new(&app);
        }));
    });

    app.run();
}
```

Creating an application window, for example, also holds the application until that window is gone. That's why it works if you create the window directly during activation.

**Comment by JakeStanger** [comment]
D'oh, I should have realised it was something that basic really. I didn't know about that `hold` method though, so that's great to know. Cheers :)
