### ISSUE TITLE
Update clone macro documentation to mention it needs glib in scope

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gtk-rs-core#129]

**Comment by fengalin** [comment]
Did you think about the examples in https://github.com/gtk-rs/gtk-rs-core/blob/master/glib-macros/src/lib.rs or is there any other places that I should check?

**Comment by GuillaumeGomez** [comment]
More like to mention that `glib` needs to be in scope.

**Comment by fengalin** [comment]
Where? Why? I mean, I added this to the examples.

**Comment by GuillaumeGomez** [comment]
In the `clone!` macro doc. Just in the code example is far from enough. It's definitely not obvious just by reading the code example that `glib` needs to be in scope. It's just there, but we don't really know why.

**Comment by fengalin** [comment]
> It's just there, but we don't really know why.

Do we need to explain why? The compiler will complain explicitly anyway.

**Comment by GuillaumeGomez** [comment]
Yes we need to, otherwise it just says "we need glib because the dark gods from the ancient times required a sacrifice but it was to refused to them and they put the blame on glib, etc", or whatever other reason you can think of. If it's not obvious, it needs to be explained.

**Comment by fengalin** [comment]
I was not involved in the design nor the implementation of these macros. I just spent at least 2 hours reverse-engineering the code which doesn't document anything about the cyclic dependencies, nor anything required to understand how it is designed, and I still can't tell why it wasn't possible to achieve what `serde` was able to achieve. So I suggest that someone who knows better adds a commit to explain that.

**Comment by sdroege** [comment]
Maybe @gdesmott remembers something?

**Comment by gdesmott** [comment]
> Maybe @gdesmott remembers something?

Hum no, I wasn't involved with this macro.

**Comment by sdroege** [comment]
Hm I thought the concern here was generally about the proc-macro-crate which is also used by the other macros. But that was apparently not added in your versions yet and was added much later by @GuillaumeGomez so he should be the best person to explain things ;) Sorry

**Comment by GuillaumeGomez** [comment]
I basically asked to add this in the documentation:

> The `clone!` macro is expecting to have `glib` in scope in order to call traits from it, so please be sure it's available.

Doesn't seem too much for me...

**Comment by sdroege** [comment]
And yes that would be good to document, but also it's unfortunate that this is needed at all :)

**Comment by GuillaumeGomez** [comment]
glib is very rarely a direct dependance so we have the choice between trying to guess which crate to use for it or simply ask nicely our users to import it in the scope. :)

**Comment by GuillaumeGomez** [comment]
Also, this issue hasn't been fixed yet so re-opening. :)

**Comment by fengalin** [comment]
@GuillaumeGomez: First of all, and because the rest of this message might sound a bit negative, I'd like to express that I appreciate you as a person!

A few weeks ago, I told you I was finding it often painful contributing to `gtk-rs`. Let's face it: we almost always disagree on general technical and project management topics. During a technical review, I'd expect we would discuss design choices or you'd provide feedback on details I would have overlooked, instead you often come up with what I feel like a radical iconoclastic position on a secondary concern. These feelings kept growing to a point where it's not fun anymore, so I decided it was time to step back from the projects. I might contribute again should a change be needed for `gstreamer-rs`, but that's it.

I hope everything will go smoothly for the release. See you later at a Rust event!

**Comment by GuillaumeGomez** [comment]
I'm sad to hear about it... I understand your frustration because you worked on both a very big code change and something that changed the API (making the functions more rust-convenient). I was very worried that I might be missing something but in the end it all worked out perfectly even though it tooks months to finally get merged.

This time, I asked to add a sentence in documentation because of how the glib `clone!` macro works: it needs to be in scope and I wanted it to be written in the documentation alongside the code examples you updated. Maybe I wasn't clear on what I asked or maybe you misunderstood. Well, I guess it doesn't matter.

Your contributions were very appreciated and you are very welcome to come back contribute any time you want. In the meantime, hope we'll be able to see each others at a conference or a hackfest (or both!). Good continuation!
