### ISSUE TITLE
syn version too low in glib-macros

### ISSUE THREAD

**Issue by bragefuglseth** [gtk-rs/gtk-rs-core#1300]
This leads to `cargo update` being necessary in some situations to make building possible at all.

[reference](https://matrix.to/#/!CxdTjqASmMdXwTeLsR:matrix.org/$170717174794693fouos:matrix.org?via=matrix.org&via=gnome.org&via=tchncs.de)

**Comment by bilelmoussaoui** [comment]
for reference
![image](https://github.com/gtk-rs/gtk-rs-core/assets/7660997/1165d590-838c-4e1d-96bf-0a69ab90f100)

**Comment by sdroege** [comment]
https://github.com/dtolnay/syn/commit/97f8eb889ffff8bfa6c0eac4f971da8cf1fda5d7

Needs at least 2.0.32.
