### ISSUE TITLE
from_glib_ptr_borrow : Consider taking a *mut pointer to object

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk-rs-core#1373]
Since we usually use *mut for GObjects, it would make sense to take a `*const *mut` or a `&*mut`. The latter one is what I usually have in my code so far.

**Comment by sdroege** [comment]
Should ideally use a reference as that makes the lifetime tracking work better and makes it harder to use it wrong. Not sure why I didn't do that. I'll look into that again :)

**Comment by sdroege** [comment]
Can you try if https://github.com/gtk-rs/gtk-rs-core/pull/1375 makes usage easy for you?
