### ISSUE TITLE
[FEATURE REQUEST] Sync for ThreadGuard

### ISSUE THREAD

**Issue by misson20000** [gtk-rs/gtk-rs-core#1385]
Is there a reason it doesn't implement Sync? Seems to me like it should be fine to implement Sync for ThreadGuard.

**Comment by sdroege** [comment]
It doesn't implement `Sync` right now because that wasn't needed yet and nobody thought of adding it. I don't see a problem with adding it. Do you want to provide a PR doing that?

**Comment by bilelmoussaoui** [comment]
See also #1082
