### ISSUE TITLE
[DISCUSSION] Automatic `ensure_type()`

### ISSUE THREAD

**Issue by DaKnig** [gtk-rs/gtk-rs-core#1401]
look at this [boilerplate](https://github.com/DaKnig/DewDuct/blob/6ab229e2f7e3146e829257c18348541c39a953a5/src/channel_page.rs#L54). each type has to specify what other custom types it depends on, forming a kind of a tree that devs need to maintain. this leads to code duplication (I have this line at least 4 times), maybe we could solve this.
this is also confusing to beginners and adds extra burden...

proposed ideas:
- maybe `#[template_child]` macro can check if the item has `IsA<Object>` and if so, `ensure_type()` on it automatically. is that possible? what would it take?
- maybe have a list of type in some top level module (like window or application or whatever) with a list of all types we provide, then `ensure_type` them all whenever any type in the module is loaded?
- other ideas?

we have most of the information to do it automatically. I think it should be done.

**Comment by bilelmoussaoui** [comment]
It is already called automatically for types that are used in TemplateChild

**Comment by DaKnig** [comment]
my bad! I was able to remove all but the last one! thanks!
