### ISSUE TITLE
[HELP] glib::MainContext::channel removal missing from changelog

### ISSUE THREAD

**Issue by kpcyrd** [gtk-rs/gtk-rs-core#1467]
Hello! :) I'm trying to port an application from glib 0.14 to 0.20 and noticed `glib::MainContext::channel` doesn't exist anymore, but it's mot obvious how to rewrite my application to make it work again. Do you have any pointers? :)

fyi I also noticed https://crates.io/crates/libappindicator points to the gtk-rs github org, but I couldn't find it's git repository unfortunately.

The code I'm trying to port is on github:

https://github.com/kpcyrd/arch-audit-gtk/blob/391bd91795ac50d8a0f8bbd3ff3b3797099cd3ad/src/gui.rs#L141

**Comment by sdroege** [comment]
See https://gtk-rs.org/blog/2024/06/01/new-release.html#removal-of-glib-channels
