### ISSUE TITLE
[FEATURE REQUEST] `Properties` derive macro shouldn't import `PropertyGet`

### ISSUE THREAD

**Issue by kawadakk** [gtk-rs/gtk-rs-core#1501]
`Properties` [imports](https://gtk-rs.org/gtk-rs-core/stable/0.20/docs/src/glib_macros/properties.rs.html#761) [`PropertyGet`](https://gtk-rs.org/gtk-rs-core/stable/0.20/docs/glib/property/trait.PropertyGet.html) into an outer scope, changing the method resolution behavior.

Recently I learned about the [`Properties` derive macro](https://gtk-rs.org/gtk-rs-core/stable/0.20/docs/glib/derive.Properties.html), and when I tried to replace manual implementations with that, I got type mismatch errors in nearby code:

```
error[E0277]: expected a `Fn(&std::vec::Vec<std::string::String>)` closure, found `usize`
   --> xxxxxxxx.rs:99:51
    |
 99 |                                           foo.get(i)
    |                                               --- ^ expected an `Fn(&std::vec::Vec<std::string::String>)` closure, found `usize`
    |                                               |
    |                                               required by a bound introduced by this call
    |
    = help: the trait `for<'a> Fn(&'a std::vec::Vec<std::string::String>)` is not implemented for `usize`
note: required by a bound in `glib::property::PropertyGet::get`
   --> xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.20.2/src/property.rs:67:18
    |
67  |     fn get<R, F: Fn(&Self::Value) -> R>(&self, f: F) -> R;
    |                  ^^^^^^^^^^^^^^^^^^^^^ required by this bound in `PropertyGet::get`
```

Before the change, the `get` call was resolved to `<[String]>::get` through a deref of `foo: &Vec<String>`. With `PropertyGet` in scope, it gets resolved to [`<Vec<String> as PropertyGet>::get`](https://gtk-rs.org/gtk-rs-core/stable/0.20/docs/glib/property/trait.PropertyGet.html#tymethod.get).

**Comment by sdroege** [comment]
That's indeed not great. Do you want to provide a PR for fixing that?

**Comment by kawadakk** [comment]
Will do!

**Comment by sdroege** [comment]
Thanks! If you find the same issue elsewhere in that macro (with that or another trait), feel free to take care of that at the same time :)
