### ISSUE TITLE
object_subclass macro creates mutable reference to mutable static

### ISSUE THREAD

**Issue by felinira** [gtk-rs/gtk-rs-core#1516]
I stumbled upon this bit:

https://github.com/gtk-rs/gtk-rs-core/blob/b97554d03ae9ae8f1c56e0e61f55d2612e1be271/glib-macros/src/object_impl_attributes/subclass.rs#L106

which throws the following warning (which is then swallowed because it's coming from a macro invocation):

> creating a mutable reference to mutable static is discouraged
> for more information, see issue #114447 <https://github.com/rust-lang/rust/issues/114447>
> this will be a hard error in the 2024 edition

This will fail to compile in rust 2024 either way, so we need to deal with this before upgrading. However, this is creating a mutable temporary reference that is then converted into a pointer and subsequently dropped. We should use `std::ptr::addr_of_mut!()` instead, and also make sure we are actually using it correctly here.

**Comment by sdroege** [comment]
Yes, this code is from before `addr_of_mut!` was stable :) You make a PR?
