### ISSUE TITLE
[FEATURE REQUEST] MountExt::eject_with_operation Does Not Kill Power to the Drive After Ejection

### ISSUE THREAD

**Issue by iamkartiknayak** [gtk-rs/gtk-rs-core#1528]
**Description:**
While using the `MountExt::eject_with_operation` method in the gio library to eject a drive, the method successfully unmounts the drive but does not kill power to the drive after ejection. As a result, the drive remains powered on, which could cause confusion for users expecting the drive to power down after ejection.

**Current behavior:**
- Internal HDD is unmounted (desired)
- `External HDD` is ejected (device has light after eject)
- `2GB Transcend USB Flash Drive`  is ejected (device has light & not properly ejected).
- `64GB Sandisk Pendrive` is ejected but may still have power (no light for device)

**Expected behavior:**
Kill power to external USB devices when ejected.

**Code (Current Impl):**
```rust
 MountExt::eject_with_operation(
          &mount,
          gio::MountUnmountFlags::NONE,
          gio::MountOperation::NONE,
          gio::Cancellable::NONE,
          move |result| {
              log::info!("unmount {}: result {:?}", name, result);
          },
      );
```

**Comment by sdroege** [comment]
You'll want to report this lower in the stack. The Rust bindings don't implement the actual functionality for this. You don't say which platform this is on, so I can't give you more advice than to report it at https://gitlab.gnome.org/GNOME/glib/ as the next step but they'll probably send you further down the stack too.
