### ISSUE TITLE
[BUG] GLib structured logger duplicates CODE_FILE, CODE_LINE, and CODE_FUNC

### ISSUE THREAD

**Issue by swsnr** [gtk-rs/gtk-rs-core#1537]
**Bug description**

When `GLibLoggerFormat::Structured` is used, the `Log::log` implementation of `GLibLogger` calls `GlibLogger::write_log_structured`, passing the log record's file, line, and module_path as line, file, and function name respectively.

`GlibLogger::write_log_structured` then calls `log_structured!`, passing the line, file, and function name as the `CODE_FILE`, `CODE_LINE` and `CODE_FUNC` fields respectively.

However, the `log_structured!` then _again_ adds `CODE_FILE`, `CODE_LINE`, and `CODE_FUNC`, using the values of `file!()`, `line!()`, and a custom `function_name!()` respectively.

Hence, any log event from the structured logger ends up with duplicated `CODE_*` fields, where the duplicates always reference the `GLibLogger::write_log_structured` call site.

Is this intended behaviour?

**Comment by sdroege** [comment]
This is not intended behaviour. This shouldn't call the `log_structured!` macro but instead just directly log things.

Do you want to provide a PR for fixing that?

**Comment by swsnr** [comment]
I can try. I'd also try to write a test for this 🙂

**Comment by sdroege** [comment]
Thanks, let me know if you get stuck somewhere / have questions :)
