### ISSUE TITLE
[BUG] The function `pango::LayoutLine::x_ranges` return a malformed value

### ISSUE THREAD

**Issue by GrounzerLiu** [gtk-rs/gtk-rs-core#1563]
**Bug description**

[Pango.LayoutLine.get_x_ranges](https://docs.gtk.org/Pango/method.LayoutLine.get_x_ranges.html)
The Pango documentation states that the length of the `ranges` is `2 * n_ranges`.

```rust
    pub fn x_ranges(&self, start_index: i32, end_index: i32) -> Vec<i32> {
        unsafe {
            let mut ranges = std::ptr::null_mut();
            let mut n_ranges = std::mem::MaybeUninit::uninit();
            ffi::pango_layout_line_get_x_ranges(
                self.to_glib_none().0,
                start_index,
                end_index,
                &mut ranges,
                n_ranges.as_mut_ptr(),
            );
            FromGlibContainer::from_glib_full_num(ranges, n_ranges.assume_init() as _)
        }
    }
```
Here, `FromGlibContainer::from_glib_full_num(ranges, n_ranges.assume_init() as _)` should be `FromGlibContainer::from_glib_full_num(ranges, (2 * n_ranges.assume_init()) as _)`.

**Comment by sdroege** [comment]
Thanks, see https://github.com/gtk-rs/gtk-rs-core/pull/1564
