### ISSUE TITLE
[FEATURE REQUEST] Make `SignalBuilder::accumulator` closure easier to use.

### ISSUE THREAD

**Issue by PJungkamp** [gtk-rs/gtk-rs-core#1580]
The current function definition for the `SignalHandler::accumulator` is `Fn(&SignalInvocationHint, &mut Value, &Value) -> bool`. The returned bool decides on the control flow of the signal emission. Could we migrate to a `Fn(&SignalInvocationHint, &Value, &Value) -> std::ops::ControlFlow<Value, Value>`?

This would allow for nicer bindings in e.g. #214 and I'd like it to be in the same release as #1575 since `class_handler` and `accumulator` are tightly related.

@sdroege What do you think?

**Comment by PJungkamp** [comment]
As far as I can tell I'd only adjust the type signatures of the accumulator functions + fields and update the trampoline.

https://github.com/gtk-rs/gtk-rs-core/blob/b8c3023f3399bf2d2e46fe8f48f12996fd97bc39/glib/src/subclass/signal.rs#L627-L665

Something like this should work for the trampoline.

```rs
let res = match (accumulator.1)(&SignalInvocationHint(*ihint), return_accu, handler_return) {
    ControlFlow::Continue(val) => {
        *return_accu = val;
        true.into_glib()
    }
    
    ControlFlow::Break(val) => {
        *return_accu = val;
        false.into_glib()
    }
};

**Comment by sdroege** [comment]
Your version would always require a copy of the accumulator value, which is fine for simple types like bools but for strings it would already be a `strdup()` every time.

Maybe the accumulator can be changed from a mutable reference to the value itself?

**Comment by sdroege** [comment]
You can also replace it with a `Value::uninitialized()` (which creates a zeroed-out `GValue`), but yes that should work. Should be effectively the same, but having `G_TYPE_INVALID` (i.e. `Value::uninitialized()`) in there is probably more descriptive when someone has to look at this in a debugger. Do you want to create a PR?

**Comment by PJungkamp** [comment]
Will do! Just wanted some feedback on deviating from the idea of deviating from the C function signature here.

Thank you for your quick responses!
