### ISSUE TITLE
Docs for RegistrationBuilder are missing

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk-rs-core#1597]
Couldn't see why on first glance, but the docs for the return type of 

<https://gtk-rs.org/gtk-rs-core/git/docs/gio/struct.DBusConnection.html#method.register_object>

are missing

**Comment by sdroege** [comment]
Because it's not exported at all. `mod dbus_connection` and no `pub use dbus_connection::RegistrationBuilder` in `src/lib.rs`. See https://github.com/gtk-rs/gtk-rs-core/pull/1598
