### ISSUE TITLE
`g_uri_parse_scheme()` no longer exposed

### ISSUE THREAD

**Issue by philn** [gtk-rs/gtk-rs-core#164]
The `g_uri_parse_scheme()` is no longer available for builds below `v2_66` while that API has been available since GLib 2.16. https://developer.gnome.org/glib/stable/glib-URI-Functions.html#g-uri-parse-scheme

Can we have it back? Ubuntu 20.04 LTS doesn't have glib 2.66.

**Comment by bilelmoussaoui** [comment]
It's there ? https://github.com/gtk-rs/gtk-rs-core/blob/61197efce69801419f12561cc3f2dfa28aef69ee/glib/src/auto/uri.rs#L301

**Comment by philn** [comment]
In `Uri` yes, which is available for v2_66 only ;) https://gtk-rs.org/gtk-rs-core/stable/latest/docs/glib/struct.Uri.html#method.parse_scheme

**Comment by GuillaumeGomez** [comment]
Outch, nice finding. Wanna send a PR for it?

**Comment by philn** [comment]
> Outch, nice finding. Wanna send a PR for it?

Sure, maybe tomorrow ;)

**Comment by GuillaumeGomez** [comment]
Or even monday, no rush. ;)

Btw: send it to the master branch, we'll cherry-pick it to the 0.14 branch afterwards.
