### ISSUE TITLE
Glib: tests failed on fedora copr aarch64

### ISSUE THREAD

**Issue by remilauzier** [gtk-rs/gtk-rs-core#166]
**Bug description**
https://download.copr.fedorainfracloud.org/results/remilauzier/gtk/fedora-rawhide-aarch64/02305289-rust-glib/builder-live.log.gz

error[E0308]: mismatched types
   --> src/gstring.rs:654:31
    |
654 |                 ffi::g_strdup(std::ptr::null::<i8>()),
    |                               ^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

**Comment by sdroege** [comment]
Indeed. Do you want to provide a PR for that test to simply add a `as *const _` cast there? Then it should figure out the right thing for all platforms.

**Comment by remilauzier** [comment]
There is 7 error in total and i am not sure where to fix all of these.

**Comment by sdroege** [comment]
Which ones are you not sure about?

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/175 for a try. Please confirm that this actually fixes all the errors for you on ARM.
