### ISSUE TITLE
sys: include license file in the crate source

### ISSUE THREAD

**Issue by remilauzier** [gtk-rs/gtk-rs-core#172]
[graphene-sys-0.14.0.zip](https://github.com/gtk-rs/gtk-rs-core/files/6729071/graphene-sys-0.14.0.zip)

The file is not present when fedora download the crate from crate.io

**Comment by sdroege** [comment]
That's a problem for all the -sys crates.

**Comment by decathorpe** [comment]
The gobject-sys crate is still missing a license file as of version 0.15.5.
