### ISSUE TITLE
 gio::File::new_tmp argument should be of type Option<...>

### ISSUE THREAD

**Issue by A6GibKm** [gtk-rs/gtk-rs-core#187]
Following the docs https://developer.gnome.org/gio/stable/GFile.html#g-file-new-tmp, the argument can be set as null when one does not care about the specific file name, in
https://gtk-rs.org/gtk-rs-core/git/docs/gio/struct.File.html#method.new_tmp it even says that the function takes None for this purpose but the function does not take a Option<...> parameter.

**Comment by sdroege** [comment]
You mean `gio::File::new_tmp()` and not `::for_path()`, right? It's marked `nullable` in the .gir file, so unclear why that doesn't have any effect here. Needs some investigation in `gir`.

For the 0.14 release we'd need to add a new function that allows `Option` to not break the API.

**Comment by A6GibKm** [comment]
> You mean `gio::File::new_tmp()` and not `::for_path()`, right? It's marked `nullable` in the .gir file, so unclear why that doesn't ...

Yeah.
