### ISSUE TITLE
[BUG] MainContextAcquireGuard not exported?

### ISSUE THREAD

**Issue by lunaryorn** [gtk-rs/gtk-rs-core#193]
**Bug description**

`MainContextAcquireGuard` doesn't seem to be exported in glib 0.14.1 (`use glib::MainContextAcquireGuard` fails to compile), which makes it impossible to pass the guard around to transfer the guard.

Rustdoc also fails to find the definition for this type at <https://docs.rs/glib/0.14.1/glib/struct.MainContext.html#method.acquire>:

![grafik](https://user-images.githubusercontent.com/224922/125044895-b7512300-e09c-11eb-9bf7-cae177a4dd64.png)

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/194 for the fix.

> Rustdoc also fails to find the definition for this type at https://docs.rs/glib/0.14.1/glib/struct.MainContext.html#method.acquire:

You probably want to use the docs at https://gtk-rs.org/gtk-rs-core/ . They're more complete than docs.rs.

**Comment by sdroege** [comment]
Will be in glib 0.14.2 in an hour or so

**Comment by lunaryorn** [comment]
Thanks :pray:
