### ISSUE TITLE
[BUG] can't create "PdfSurface" in cairo-rs

### ISSUE THREAD

**Issue by Yoxem** [gtk-rs/gtk-rs-core#197]
**Bug description**

I tried to use the code to manipulate a PDF file

    use cairo;

    fn main(){
      let surface = gtk::cairo::PdfSurface::new(300, 500, "pdf.pdf").unwrap();
      let context = cairo::Context::new(&surface);
    }

but it generated a error:

  error[E0433]: failed to resolve: could not find `PdfSurface` in `cairo`

**Backtrace**
Cargo.toml

    [dependencies]
    cairo-rs = "0.14.1".

Part of error message:
    error[E0433]: failed to resolve: could not find `PdfSurface` in `cairo`
     --> src/main.rs:5:24
      |
    5 |   let surface = cairo::PdfSurface::new(300, 500, "example.pdf").unwrap();
      |                        ^^^^^^^^^^ could not find `PdfSurface` in `cairo`

**Comment by bilelmoussaoui** [comment]
You have to enable the pdf feature for your code to work

**Comment by Yoxem** [comment]
I have change the cargo.toml to that:
    [dependencies]
    cairo-rs = {"0.14.1". features = ["pdf"]}

code change to that:
    use cairo::*;
    ....
    let surface = PdfSurface::new(300, 500, "example.pdf").unwrap();

The code still was:

error[E0433]: failed to resolve: use of undeclared type `PdfSurface`
 --> src/main.rs:5:19
  |
5 |     let surface = PdfSurface::new(300, 500, "example.pdf").unwrap();
  |                   ^^^^^^^^^^ use of undeclared type `PdfSurface`
