### ISSUE TITLE
No bindings for the g_win32 methods

### ISSUE THREAD

**Issue by nacho** [gtk-rs/gtk-rs-core#2]
There seems to be missing all those methods for windows. Probably because they are not part of the gir on linux

- [ ] `g_win32_check_windows_version ()`
- [ ] `g_win32_get_command_line ()`
- [ ] `g_win32_error_message ()`
- [ ] `g_win32_getlocale ()`
- [ ] `g_win32_get_package_installation_directory ()`
- [x] `g_win32_get_package_installation_directory_of_module ()`
- [ ] `g_win32_get_package_installation_subdirectory ()`
- [ ] `g_win32_get_windows_version ()`
- [ ] `g_win32_locale_filename_from_utf8 ()`

Details at https://developer.gnome.org/glib/stable/glib-Windows-Compatibility-Functions.html

**Comment by sdroege** [comment]
Some are there but yes, many are missing :) You'd have to add them manually like the ones that already exist. Any specific ones you're missing?

**Comment by nacho** [comment]
The one that I currently need is `g_win32_get_package_installation_directory_of_module`. I made a quick git grep in the repo and I could not find any g_win32 method.

**Comment by sdroege** [comment]
gio/src/win32_input_stream.rs for example.

**Comment by sdroege** [comment]
I guess there's more to fix here.

**Comment by bilelmoussaoui** [comment]
I updated the issue and added a list of the functions based on GLib docs which I linked in the original issue as well

**Comment by bilelmoussaoui** [comment]
Can be closed now

**Comment by sdroege** [comment]
That were all?
