### ISSUE TITLE
GEnum is a bit strange

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gtk-rs-core#20]
I find the `GEnum` a bit strange. For reference:

```rust
#[derive(Debug, Eq, PartialEq, Clone, Copy, glib::GEnum)]
#[repr(u32)]
#[genum(type_name = "SimpleObjectAnimal")]
enum Animal {
    Goat = 0,
    #[genum(name = "The Dog")]
    Dog = 1,
    #[genum(name = "The Cat", nick = "chat")]
    Cat = 2,
}
```

Why not having a `gvariant` for variants instead? It got me quite confused at first. Also, what's the point of the derive if we need to add `#[genum(type_name = "SimpleObjectAnimal")]`?

**Comment by sdroege** [comment]
I think there's nothing to be done here anymore
