### ISSUE TITLE
Simplify ParamSpec::new_override

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs-core#201]
Currently ParmSpec::new_override takes two parameters. The property name & the ParamSpec. Instead, it should take the type we want to override it's property and the property we want to override.

The code then should check whether it's an Interface or an Object and use `Interface::from_type` / `ObjectClass::from_type`

**Comment by sdroege** [comment]
I would keep the old version around too and just add an additional version like you suggest. Otherwise sounds good to me

**Comment by sdroege** [comment]
`_simple()`?
