### ISSUE TITLE
missing methods for gio::File

### ISSUE THREAD

**Issue by A6GibKm** [gtk-rs/gtk-rs-core#203]
Missing:

 - [x] `replace_contents_bytes_async`
 - [x] `copy_async`
 - [x] `copy_async_future`
 - [x] `load_partial_contents_async`
 - [ ] `load_partial_contents_async_future`
 - [x] `measure_disk_usage_async`
 - [x] `measure_disk_usage_async_future`
 - [x] `query_settable_attributes`
 - [x] `query_writable_namespaces`
 - [ ] `set_attribute`

**Comment by bilelmoussaoui** [comment]
@A6GibKm do  you want to contribute some of those for the next release? :)

**Comment by A6GibKm** [comment]
I am a bit low on time, so I dont think ill be able to.

**Comment by sdroege** [comment]
> [ ] `set_attribute`

See https://github.com/gtk-rs/gtk-rs-core/issues/40 , not handling that one here.

**Comment by sdroege** [comment]
Note that we have lots of type-specific `set_attribute_XXX()` functions.

**Comment by sdroege** [comment]
>     * [ ] load_partial_contents_async_future

This one has a processing model that makes not much sense for futures.

**Comment by sdroege** [comment]
@A6GibKm See https://github.com/gtk-rs/gtk-rs-core/pull/319 . Let me know if anything else is still missing for you and if all that behaves correctly.

**Comment by A6GibKm** [comment]
> @A6GibKm See #319 . Let me know if anything else is still missing for you and if all that behaves correctly.

Certainly works for me, I haven't tested it yet (as the places where I need it use libadwaita-rs which cannot be build with master). Just note that copy has an optional progress callback

![image](https://user-images.githubusercontent.com/11528996/140104534-f712cb43-3cd6-4e26-8254-f6d0417b044a.png)

and copy_async's callback is not optional (can be NULL according to https://docs.gtk.org/gio/method.File.copy_async.html)

![image](https://user-images.githubusercontent.com/11528996/140104911-c929eee7-f251-4a0d-a92f-cd16eb78c930.png)

**Comment by sdroege** [comment]
Please create a separate issue for that
