### ISSUE TITLE
Add bindings for GInitiable / GAsyncInitiable

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#22]

**Comment by sdroege** [comment]
Bindings are there but calling/checking on construction is still awkward because of the library boundary. CC @jf2048

**Comment by jf2048** [comment]
I think the best we could do is call `g_type_interfaces` and do some string comparisons on the type name before calling `g_object_new`, but that's not really appealing

**Comment by sdroege** [comment]
Yeah and `dlsym()` the `g_initable_get_type()` from the current process. That's the best I came up with so far too :)

**Comment by jf2048** [comment]
A little bit better would be:

- Use `Type::qname` instead to do quark comparisons
- Error from `Object::new`, `Object::with_type` immediately if the interface is detected
- Require use of other constructors `Initable::new`, `Initable::with_type`, `AsyncInitable::new` etc for those classes
