### ISSUE TITLE
[FEATURE REQUEST] would it be possible for the `*-sys` crates to avoid the heavy dependencies?

### ISSUE THREAD

**Issue by nagisa** [gtk-rs/gtk-rs-core#225]
I'm making a library that uses the C bindings to the glib and other libraries of the family. Currently this happens via the `-sys` crates.

The reason I chose to interface with the the unsafe C APIs was to reduce the maintenance burden with keeping up with the new versions of the `g*` family of crates. I have other libraries exposed in my public API and I must version my library along with those other libraries instead. As a result, if I depended upon the `glib` crate directly, users of my crate would have a harder time picking a version that matches the versions of `glib` and similar libraries they use.

I didn't particularly mind if my users ended up with duplicate versions of the `g*-sys` crates in their dependency tree. However this was predicated on the expectation that the `-sys` crates are quick to build (which is generally true for the `sys` crates). Turns out the `glib-sys` depend on `system-deps` crate, and that in turns pulls in an entire proc-macro machinery, bringing the total number of dependencies to 44 and build times to 10+ seconds on a modern CPU.

Is there any way the `system-deps` dependency could be avoided? The `pkg-config` by itself has no dependencies, for example.

**Comment by GuillaumeGomez** [comment]
I agree with you. However, I think this debate has been "lost" already: by commodity and for code readability, `system-deps` will continue to use proc-macro crates, forcing us to have a lot of crates...

**Comment by GuillaumeGomez** [comment]
I opened gdesmott/system-deps#49. If they agree, I'll try to remove as many dependencies as possible (because we definitely want to continue to use this crate which is very convenient!).

**Comment by sdroege** [comment]
> turns pulls in an entire proc-macro machinery

In my experience that's usually not much of a problem because it's already pulled in by some other dependency anyway. It seems hard to avoid all dependencies that potentially use proc macros.

> bringing the total number of dependencies to 44 and build times to 10+ seconds on a modern CPU.

OOC, what's the use-case where 10 extra seconds (initial!) build time are such a big problem?

**Comment by GuillaumeGomez** [comment]
Well, I opened https://github.com/gdesmott/system-deps/pull/50 in any case, that should makes things faster.

**Comment by sdroege** [comment]
@nagisa Is there anything else to do here now that system-deps has fewer dependencies?

**Comment by GuillaumeGomez** [comment]
Publish the new system-deps version and update it in our crates I'd assume. ;)

**Comment by sdroege** [comment]
Everything updated to the new version.
