### ISSUE TITLE
Add bindings for g_signal_connect_object()

### ISSUE THREAD

**Issue by haecker-felix** [gtk-rs/gtk-rs-core#23]
More details: https://valadoc.org/gobject-2.0/GLib.Signal.connect_object.html

**Comment by jf2048** [comment]
If #338 is good enough then possibly this could be closed. It should be usable for the same purpose. `g_signal_connect_object` can't really be bound as-is because there is nowhere to pass in the trampoline.

**Comment by sdroege** [comment]
Yeah I think this can be closed.
