### ISSUE TITLE
future methods for gio::File signature aren't idiomatic

### ISSUE THREAD

**Issue by A6GibKm** [gtk-rs/gtk-rs-core#232]
The signature for replace_contents_async_future is a little awkward

``` rust
fn replace_contents_async_future<B: AsRef<[u8]> + Send + 'static>(
        &self,
        contents: B,
        etag: Option<&str>,
        make_backup: bool,
        flags: FileCreateFlags,
    ) -> Pin<
        Box<
            dyn std::future::Future<Output = Result<(B, glib::GString), (B, glib::Error)>>
                + 'static,
        >,
    >;
```
It does not allow for stuff like `file.replace_contents_async_future(...).await?`.

It should return a simple `Result<Something, glib::Error>`. On the other hand whats up with these `future` methods naming shcme? Could not they just be `replace_contents_future`?

**Comment by sdroege** [comment]
> It should return a simple `Result<Something, glib::Error>`.

This is so that you can re-use the buffer that you passed in.

>  On the other hand whats up with these `future` methods naming shcme? Could not they just be `replace_contents_future`?

That could make sense, yes.

**Comment by A6GibKm** [comment]
Would not in that case make more sense to return `(B, Result<<String>, glib::Error>)`? Is the same return for both AsRef objects?

**Comment by sdroege** [comment]
> Would not in that case make more sense to return `(B, Result<<String>, glib::Error>)`? Is the same return for both AsRef objects?

With what we have now you can do

```rust
let (content, _) = file.replace_contents_async_future(...)
    .await
    .map_err(|err| err.1)?;
```

That would be more ugly with your suggestion.

> EDTI: Also do we need to return B to re use it? if it is passed as a ref to the replace_contents method we can still keep using it.

It can't be passed by reference. The future has to own the memory unfortunately.

**Comment by A6GibKm** [comment]
Fair points, just wanted to point out that it is not possible to use the `?` operator inside a function returning a `anyhow::Result`.

**Comment by sdroege** [comment]
Yeah it's not ideal but seemed like the least worst approach to me :)

**Comment by A6GibKm** [comment]
Closing. I will open an issue regarding the naming.
