### ISSUE TITLE
API to bridge futures and GCancellable

### ISSUE THREAD

**Issue by cgwalters** [gtk-rs/gtk-rs-core#240]
I came up with this: https://github.com/coreos/rpm-ostree/pull/3083/commits/66b6e7cf4149cc48a96e64455ff83ef1cee51d53#diff-7939b1bb63c982978270ab1c565b42a56f7fea352ce7b2cdb792e1272fe4c6acR16
Does this API exist somewhere already?  It feels useful enough to add as an API on e.g. `GCancellable` perhaps?

**Comment by cgwalters** [comment]
(I'm not sure if there's a reactor-independent way to do the bridging though...I guess it'd make the most sense to default to the glib mainloop, but hmm...I'm not totally sure right now I want to use that instead of tokio)

**Comment by ids1024** [comment]
Wouldn't [`abortable()` from `futures`](https://docs.rs/futures/0.3.16/futures/future/fn.abortable.html) work? Then just call `AbortHandle::abort` when the `GCancellable` is cancelled.

**Comment by sdroege** [comment]
That sounds potentially useful to have here, yes. I was planning to add the other way around at some point, basically a

```rust
impl GioFuture {
    fn cancel(&self) -> CancelHandle;
}
```

which would cancel the `GCancellable` of the future, and `CancelHandle` then would be a future that resolves once the cancellation happened (the future is `Drop`ed).

> I'm not sure if there's a reactor-independent way to do the bridging though

You could use the oneshot channel from the futures crate and `futures::future::select()`

**Comment by cgwalters** [comment]
Took a shot at this in https://github.com/ostreedev/ostree-rs-ext/pull/109
