### ISSUE TITLE
[BUG] glib 0.14.3 fails to typecheck / compile on non-x86 architectures

### ISSUE THREAD

**Issue by decathorpe** [gtk-rs/gtk-rs-core#244]
Version 0.14.3 of the `glib` crate does not compile on any non-x86 architecture (aarch64, armv7hfp, powerpc64le, s390x).

This commit seems to have introduced code that does not typecheck correctly on non-x86 architectures:
https://github.com/gtk-rs/gtk-rs-core/commit/9b9d47876a5898f5d9c756f8ea0f09bf5c54a204

This is the compiler error message:

```
error[E0308]: mismatched types
  --> src/variant_iter.rs:88:17
   |
88 |                 s as *const u8 as *const i8,
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
   |
   = note: expected raw pointer `*const u8`
              found raw pointer `*const i8`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0308`.
error: could not compile `glib`
```

**Comment by sdroege** [comment]
Thanks! Do you want to submit a PR for that? Doing `s as *const u8 as *const _` or just `s as *const _` should be sufficient here.

**Comment by decathorpe** [comment]
I'll verify whether this works and then submit a PR.

Though I wonder why the `glib_sys::g_variant_get_child` API is different (`*const i8` vs `*const u8`) on x86 vs. non-x86 architectures. That sounds like another issue? I've only ever seen weird `i8` vs `u8` mismatches like this when mixing-and-matching Rust primitive types (like `u8` from `bytes`) with `libc::c_char`.

**Comment by sdroege** [comment]
It's for exactly that reason: `libc::c_char`.

**Comment by decathorpe** [comment]
Oh, C is just wonderful. Unsigned vs. signed chars :) I'll have my PR ready in a few minutes.
