### ISSUE TITLE
[BUG] VariantType does not implement to_glib_full, panics

### ISSUE THREAD

**Issue by mahkoh** [gtk-rs/gtk-rs-core#248]
**Bug description**

https://github.com/gtk-rs/gtk-rs-core/blob/db041297159cab441865c7cb82b7ea8205141ace/glib/src/variant_type.rs#L99-L106

https://github.com/gtk-rs/gtk-rs-core/blob/db041297159cab441865c7cb82b7ea8205141ace/gio/src/subclass/action_group.rs#L782

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/249

**Comment by sdroege** [comment]
@mahkoh Is it blocking you currently? I would include this in the new 0.14 bugfix release but unless that's urgent for you I'd wait a few days with that.

**Comment by mahkoh** [comment]
@sdroege I've locally patched glib to fix the problem. It's not blocking me right now.

**Comment by sdroege** [comment]
Ok, let me know if you need a bugfix release on crates.io with this :) Let's hope I do that before you have to ask though!

**Comment by sdroege** [comment]
Done now, this is in 0.14.5
