### ISSUE TITLE
[FEATURE REQUEST] Add search-query links to other gtk crates in doc search

### ISSUE THREAD

**Issue by flxzt** [gtk-rs/gtk-rs-core#253]
Until the [search for external crates](https://github.com/rust-lang/rust/issues/86715) is implemented a simple search link with the search query to the other gtk-rs crates would make browsing the docs easier.

Like this (just like the duckduckgo link):
![search-link](https://user-images.githubusercontent.com/19841886/131477655-23098034-acf2-40bf-8641-3df8c5e29b9a.png)

**Comment by GuillaumeGomez** [comment]
That's not something we can do from our side.

**Comment by flxzt** [comment]
I think so, I don't mind it
