### ISSUE TITLE
Add derive macro for structs representing GObject properties

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#27]
Kind of related to https://github.com/gtk-rs/glib/issues/637 and I would do them together in a few days.

I'll write out the whole plan here once I'm at a computer again, but the basic idea would be a derive macro and corresponding infrastructure that
- registers a GObject property per struct field, incl default, min, max values etc
- provides  a set/get property function that directly does the translation
- provides a notify function for notifying changes

The struct itself would then be stored inside the instance data in a refcell or mutex.

This should allow to bring down the boilerplate for GObject subclasses with properties considerably.

**Comment by bilelmoussaoui** [comment]
I suppose this can be closed now?
