### ISSUE TITLE
Remove iOS target from quartz_surface in cairo

### ISSUE THREAD

**Issue by Gymxo** [gtk-rs/gtk-rs-core#291]
iOS does not support the quartz_surface due to there being a lack of application services.
Due to this, regular Cairo turns off quartz by default and this error is produced when trying to compile a project that contains cairo-rs.
![5967C172-4390-4F2B-9ED8-037B6862EC3D](https://user-images.githubusercontent.com/55960119/137568265-a1da5c63-6114-4c2d-a042-06ecdfbb6dd7.png)

**Comment by sdroege** [comment]
Indeed, not sure why iOS was included there to begin with.

Do you want to provide a PR for this? Should be just a matter of

```diff
-#[cfg(any(target_os = "macos", target_os = "ios", feature = "dox"))]
+#[cfg(any(target_os = "macos", feature = "dox"))]
```

In the 5 places this is used.
