### ISSUE TITLE
Use once_cell::Lazy instead of std::sync::Once

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#30]
See summary. Simpler and less easy to get wrong.

**Comment by bilelmoussaoui** [comment]
This is only used in glib-macros, should we still port to once_cell even if we want to potentially get rid of it in the future?

**Comment by sdroege** [comment]
glib already re-exports `once_cell` or not?

**Comment by bilelmoussaoui** [comment]
Yes it does
