### ISSUE TITLE
Rename `glib::GString` to `glib::CString` to avoid confusion with the C `GString` (aka `glib::String`)

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#301]
And potentially also rename `glib::String` to `glib::StringBuilder` (which Vala did, for example), but OTOH the Rust "string builder" type is also just called `String`.

@bilelmoussaoui @GuillaumeGomez Opinions?

**Comment by pbor** [comment]
For what is worth I found `GString` super confusing at the beginning. I like the plan proposed in the last comments!

**Comment by sdroege** [comment]
> For what is worth I found `GString` super confusing at the beginning. I like the plan proposed in the last comments!

You mean removing `glib::String` (the C `GString` string builder) and keeping `glib::GString` (the string with the GLib allocator)?

**Comment by pbor** [comment]
Yes, and renaming that to `glib::String`

**Comment by sdroege** [comment]
First part in https://github.com/gtk-rs/gtk-rs-core/pull/332 . I'll do the renaming once this is in, it requires gir changes and manual changes all over the place.

**Comment by sdroege** [comment]
@GuillaumeGomez for renaming, you were very much against CString, but String would be OK for you?

**Comment by GuillaumeGomez** [comment]
I'd still prefer `GString` but don't want to drag the debate forever.

**Comment by sdroege** [comment]
IMHO `GString` is better than `String` (our thing is a `Box<str>` but `String` is a string builder!), but `CString` would be best (our thing is an owned, NUL-terminated C/FFI string just like `CString` but in addition also guaranteed UTF-8).

I'm a bit hesitant to rename it to `String` because of that :)

**Comment by sdroege** [comment]
Let's keep it like this then. No more `glib::String` and keeping `glib::GString`
