### ISSUE TITLE
Add property getter and setter that panic when an error occurs

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gtk-rs-core#307]
At the moment, when you want to get a custom property you have to accept a lot of boilerplate:

```rust
let current_state = switch
        .property("state")
        .expect("The property needs to exist and be readable.")
        .get::<bool>()
        .expect("The property needs to be of type `bool`.");
```

Typically, these properties are created within your program without any decision tree involved.
This means that you always want to panic if either `property` or `get` returns `Err`.

To accommodate this use case, I suggest to change 
`fn property<'a, N: Into<&'a str>>(&self, property_name: N) -> Result<Value, BoolError>`
to
`fn property<'a, N: Into<&'a str>, T: FromValue>(&self, property_name: N) -> T`

This would simplify the example mentioned before to this:

```rust
let current_state = switch.property::<bool>("state");
```

The old behavior could then be exposed with a method called `property_value`.

@sdroege

**Comment by sdroege** [comment]
Should maybe also make the property binding builder's `build()` panic and add a `try_build()` that checks for property existence? CC @bilelmoussaoui

**Comment by bilelmoussaoui** [comment]
> Should maybe also make the property binding builder's `build()` panic and add a `try_build()` that checks for property existence? CC @bilelmoussaoui 

Yeah, that would be nice. I will have a look at this issue today

**Comment by sdroege** [comment]
Should probably consider similar things for signal connection and emission.
