### ISSUE TITLE
New variant of ObjectExt::emit_with_name

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs-core#337]
Currently, you can emit a signal and it might returns a Option<Value>. Similar to the new property getter; we would like to have something that automatically returns `Option<T> where T:  for <'b> FromValue<'b> + 'static`

**Comment by sdroege** [comment]
Or even better something that returns `()` for `None` (and panics otherwise), and `T` for other cases

**Comment by GuillaumeGomez** [comment]
I'm not sure to understand why we would want to return `T` directly. Why would we want to remove the `Option` wrapping?
