### ISSUE TITLE
Rename glib::DateTime constructors

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs-core#342]
Currently, glib::DateTime has some constructors that could possibly be renamed

- `new_local` -> `local`
- `new_now` -> `now`
- `new_now_local` -> `now_local`
- `new_now_utc` -> `now_utc`
- `new_utc` -> `utc`

**Comment by bilelmoussaoui** [comment]
glib::TimeZone has similar ones as well

**Comment by bilelmoussaoui** [comment]
Similarly, there's the ParamSpec case. @fengalin I heard you had a different opinion than dropping the new_ prefix ?

**Comment by fengalin** [comment]
@bilelmoussaoui : I found [an issue](https://github.com/gtk-rs/gtk-rs-core/issues/76) which links to a discussion on this topic. I'm not quite sure what would be the best way to handle this. My main concern is that it shouldn't conflict with getters or be confusing.

**Comment by sdroege** [comment]
For datetime/timezone that change is quite clearly an improvement then, for paramspec maybe not. But maybe paramspec should also have specific constructors (`glib::ParamSpecInt::new()` instead of `glib::ParamSpec::new_int()`).

**Comment by fengalin** [comment]
I agree:

- The `datetime` "constructors" are kind of getters, and this would be akin to `Instant::now` & co.
- I like the idea of `ParamSpecInt::new`.

**Comment by sdroege** [comment]
Let's go with that then?
