### ISSUE TITLE
Consistently name macros

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#343]
Currently many macros have a `G`/`g` as prefix while others don't. We should do this consistently.

Any objections to drop the prefix on all macros?

CC @bilelmoussaoui @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Can you show examples please?

**Comment by sdroege** [comment]
> Can you show examples please?

https://gtk-rs.org/gtk-rs-core/git/docs/glib_macros/index.html

**Comment by GuillaumeGomez** [comment]
I think we should do the following: any attribute/derive macro should start with `g` and the others shouldn't. The only thing I don't have an opinion on is either we should keep the capital letters or not...

So from the link you provided, only `clone` shouldn't be prepended.

**Comment by sdroege** [comment]
IMO none of them should have a `G` at the front

**Comment by bilelmoussaoui** [comment]
- For derive macros we currently have: 1 without a prefix, the rest with one. I think we should drop the prefix from the rest
- For macros like clone/gclosure (in the PR), i think the g prefix should be dropped as well; most of the times you will just call `glib::clone` / `glib::closure` without having to have it in scope. 
- For attribute macros, we only have a gflags that has a g prefix; I don't think it makes sense there neither :-)

**Comment by A6GibKm** [comment]
+1, those prefixes seem like a C artifact.

**Comment by GuillaumeGomez** [comment]
So that mean the derive will become `Boxed` or `Enum`. It's hard to make the name less informative at this point... As for the attributes, `flags` means literally nothing as well...

**Comment by A6GibKm** [comment]
> So that mean the derive will become Boxed or Enum. It's hard to make the name less informative at this point... As for the attributes, flags means literally nothing as well...

The derive will become `glib::Enum`, of course if you import `use glib::Enum` it it is not clear, but the same could be said about a bunch of structs if imported blindly.

**Comment by sdroege** [comment]
> So that mean the derive will become `Boxed` or `Enum`. It's hard to make the name less informative at this point... As for the attributes, `flags` means literally nothing as well...

It's a `glib::Enum` then, which is very closely connected to `glib::EnumClass`. Same for flags, etc.
`glib::Variant` would derive the things needed for a... `glib::Variant`.

Currently then prefix on the macros is odd also because there's no such prefix on the corresponding types.

**Comment by GuillaumeGomez** [comment]
But in `glib` it'll be `crate::Enum`.

**Comment by sdroege** [comment]
Just like it's already `crate::EnumClass`, etc. But also these derive macros are not even used inside `glib` apart from re-exporting them, so that's not really a meaningful concern.

**Comment by GuillaumeGomez** [comment]
We seem to only use them in subclasses and they already use `glib::`, so I guess it's fine.

**Comment by sdroege** [comment]
That only brings us one problem

```
269 | #[proc_macro_derive(Enum, attributes(enum))]
    |                                      ^^^^ expected identifier, found keyword
```

Suggestions for how to solve this? The `#[enum]` attribute needs a different name.

**Comment by bilelmoussaoui** [comment]
Maybe it should be member ?

**Comment by bilelmoussaoui** [comment]
Same as the flags one

**Comment by sdroege** [comment]
Yeah that would even make more sense.

**Comment by bilelmoussaoui** [comment]
So, `enum_member` & `flag_member`

**Comment by sdroege** [comment]
Then there's only the `#[enum(type_name = "EnumTypeName")]` (and similar for all the other macros). Should that be `#[enum_name("EnumTypeName")]` instead maybe?

Or maybe we make this `#[type_name("Blabla")]` and use the same for all the macros? Can really only derive one of those anyway so there's no risk of conflict.

OTOH other derive macros use their macro name also as attribute name and put all the details inside the parenthesis.

For boxed we also have `#[boxed(nullable)]`, FWIW.

**Comment by bilelmoussaoui** [comment]
> `#[enum_name("EnumTypeName")]` 

sounds good to me :) especially that you probably won't have any other attributes to set for that one

**Comment by GuillaumeGomez** [comment]
Now that makes me happy. Names with meaning! :tada:

**Comment by pbor** [comment]
After doing the changes I have some doubts:

1. the `flags` macro is inconsistent with the rest... does anybody remember why this is not a `derive`?
1. given that anyway we are deviating from using the derive macro name for the attributes, I think it would be more consistent to use `#[glib_name("MyType")]` and `#[glib_nullable]` for all derive macros that support this attributes. The `glib` prefix would allow to consistently namespace the attributes.

**Comment by bilelmoussaoui** [comment]
A `#[type_name("X")]` could also be used by ObjectSubclass :-)

**Comment by sdroege** [comment]
> A `#[type_name("X")]` could also be used by ObjectSubclass :-)

No because there it's an associated type in a trait :)

> the `flags` macro is inconsistent with the rest... does anybody remember why this is not a `derive`?

Because you can't generate the `bitflags!` macro invocation from a derive macro (or anything wrapping around the actual type definition). You can only produce additional items like trait impls.

>     2\. given that anyway we are deviating from using the derive macro name for the attributes, I think it would be more consistent to use `#[glib_name("MyType")]` and `#[glib_nullable]` for all derive macros that support this attributes. The `glib` prefix would allow to consistently namespace the attributes.

Why have the glib prefix?

**Comment by pbor** [comment]
> Why have the glib prefix?

Because the attributes are not namespaces. I assume that the convention if using the same name for the attribute and the derive is to avoid conflicts with other macros. By using a `glib` namespace we should also avoid problems (unless two of these macros can be applied to the same element)

**Comment by pbor** [comment]
> Because you can't generate the `bitflags!` macro invocation from a derive macro (or anything wrapping around the actual type definition). You can only produce additional items like trait impls.
> 

The other possibility for consistency is to not use derive for any of them and instead have

`#[glib::enum_type(Foo)]`
`#[glib::flags_type(Foo)]`
`#[glib::boxed_type(Foo)]`
`#[glib::shared_boxed_type(Foo)]`

(we need the `_type` suffix or something like that because we cannot have a `#[glib::enum(Foo)]`)

**Comment by sdroege** [comment]
> The other possibility for consistency is to not use derive for any of them

That doesn't seem like an improvement. It's bad enough that we can't use derive for flags, but fortunately flags are far less common than any of the others :)

**Comment by pbor** [comment]
> That doesn't seem like an improvement. It's bad enough that we can't use derive for flags, but fortunately flags are far less common than any of the others :)

¯\_(ツ)_/¯

I guess it depends on how much we care more about consistency... `derive` is more familiar for rust users, but then again our derive macro require extra attributes, which partly defeat that. Having those custom attributes would be shorter since it is just one attribute. In fact I was thinking we could maybe have a single macro `#[glib::static_type(enum, "Foo")]` etc...

Oh well, I do not have a strong opinion on this

**Comment by sdroege** [comment]
Interesting idea. The difference is then mostly with tooling support: derive macros work fine, attribute macros and other proc macros are confusing tooling as they can't know if the input is supposed to be valid Rust and what the output is going to be.
