### ISSUE TITLE
Switch to system-deps 6

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#375]
CC @gdesmott @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
A new version was released?

**Comment by gdesmott** [comment]
Yes, I unfortunatelly had to break the API, see https://github.com/gdesmott/system-deps/pull/56

**Comment by GuillaumeGomez** [comment]
It's fine. I'll try to update in the next days.
