### ISSUE TITLE
[HELP] How to properly use `create_for_data`

### ISSUE THREAD

**Issue by Magicloud** [gtk-rs/gtk-rs-core#388]
I tried to do it as following. I got memory leakage. The last `from_raw` does not work because `ptr` is moved when calling `create_for_data`.

I am trying to do this because `ImageSurface` is not `Send`-able, when I have a "background" that is used in multiple images generation, I have to reload the file content in each thread. So I am thinking storing the `ImageSurfaceData` between threads.

```rust
let d: Box<[u8]> = ...;
let ptr = Box::leak(d);
let s = cairo::ImageSurface::create_for_data(
    ptr,
    elem.image_data.format,
    elem.image_data.width,
    elem.image_data.height,
    elem.image_data.stride,
)?;
// Operations
// let _d = unsafe { Box::from_raw(ptr) };
```

**Comment by sdroege** [comment]
See the gtk3-rs/cairo_threads example, specifically https://github.com/gtk-rs/gtk3-rs/blob/master/examples/cairo_threads/image/image_holder.rs
