### ISSUE TITLE
[FEATURE REQUEST] Support enums in Variant derive macro

### ISSUE THREAD

**Issue by jf2048** [gtk-rs/gtk-rs-core#394]
It should be possible to expand this to support all rust enums as well as `GEnum` types. Inspiration can be taken from [serde's enum serialization](https://serde.rs/enum-representations.html). There is also the (possibly unrelated) question of what to do about ffi enums, which are not currently usable from a struct with `derive(Variant)`.

In the long term, perhaps it would be better to replace this macro with a serde-compatible implementation similar to what [zbus](https://docs.rs/zvariant/2.10.0/zvariant/gvariant/index.html) does.

**Comment by sdroege** [comment]
I specifically didn't want to support enums because there's no single correct way to serialize them. We could possibly support C-style enums but I had no need for that.

I also specifically didn't want to go with serde for the derive macro because its data model does not really fit with the variant data model. Just like in zbus all kinds of workarounds would be needed.

**Comment by jf2048** [comment]
Hmm, I have a (probably opinionated) way of how to serialize enums so I can just put that in another crate for now if that's a better solution. I can let you know how it goes :smiley:

**Comment by sdroege** [comment]
I have at least 3 different ideas how enums could be serialized :)

**Comment by jf2048** [comment]
Would they all be covered by the existing serde attributes for json? That can be something to aim for.

**Comment by sdroege** [comment]
I don't think so as there's not really a 1:1 mapping between JSON (and thus the serde data model) and variants. The untagged variant in serde for example can't really be expressed (unless you express the whole thing as a `a{sv}`).

**Comment by jf2048** [comment]
My plan for now is to just use `(sv)` for everything and then allow using only `s` or `i` using an attribute if wanted, e.g. for `GEnum`s.

**Comment by jf2048** [comment]
Basic demo of how to do this with serde is here: https://github.com/jf2048/glib-serde
