### ISSUE TITLE
impl ValueType for Value should be a no-op.

### ISSUE THREAD

**Issue by mehmooda** [gtk-rs/gtk-rs-core#4]
# Problem
`Value::get()` looks like it should act like `std::convert::TryInto` but it doesn't.

```rust
let x: Value = 0i32.to_value();
let y: Value = x.get().unwrap();
```

The above panics with `WrongValueType(ValueTypeMismatchError { actual: gint, requested: GValue })`

The above code expects the Value to be a Boxed Value.

What this means is that if a function returns a T: ValueType. It is impossible for that T to be a generic (unknown) Value).

an example from gtk-rs/gtk4-rs#332

`TreemodelExtManual::get() -> Value` does not have the same semantics as `TreeModelExtManual::get<T: ValueType>() -> T` as it is not possible to get an untouched Value from it.

# Possible Solution

Make `impl ValueType for Value` act as a no-op. Similar to how `impl<T> From<T> for T` acts.

The existing behaviour of a boxed value could be created by having a `impl ValueType for Box<Value>` or even a `struct Boxed(pub Value)`

**Comment by sdroege** [comment]
@mehmooda You mentioned the idea to have a wrapper `BoxedValue` type that would have the current boxed value-in-value behaviour as a first step. That would be useful to have for the next release.

**Comment by sdroege** [comment]
See also https://github.com/gtk-rs/gtk3-rs/issues/605 for some more discussion about this

**Comment by piegamesde** [comment]
What's the relationship between `Into`, `ToValue`, `TryFrom` and `FromValue`? I noticed an `Into` implementation that allows to use `impl Into<Value>` that at least resolves the issue I had. However, I couldn't manage to make it also work in the other direction due to conflicting trait implementations.

**Comment by sdroege** [comment]
> What's the relationship between `Into`, `ToValue`, `TryFrom` and `FromValue`? I noticed an `Into` implementation that allows to use `impl Into<Value>` that at least resolves the issue I had:

The `Into` implementation in that case is the blanket implementation from std. As `Into` always takes ownership of its value this is doable and makes sense.
