### ISSUE TITLE
[FEATURE REQUEST] Add glib::subclass::Signal to prelude

### ISSUE THREAD

**Issue by A6GibKm** [gtk-rs/gtk-rs-core#408]
This is a widely used struct and it is a bit awkward to not have it in the prelude.

**Comment by sdroege** [comment]
Structs/enums don't go to the prelude, only traits do.

**Comment by sdroege** [comment]
(otherwise you get type name conflicts too easily)

**Comment by A6GibKm** [comment]
can't it be loaded by `glib::Signal` somehow?

**Comment by bilelmoussaoui** [comment]
Yes, you re-export it in lib.rs
