### ISSUE TITLE
[FEATURE REQUEST] Builder pattern: css_classes should take an iterator or a slice

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk-rs-core#411]
The method `WidgetBuilder::css_classes` should take an `I where I: IntoIterator<Item = S>, S: AsRef<String>` 

What I'm thinking:

Before:
```rust
ButtonBuilder::new()
  .css_classes(vec!["flat".to_string(), "rounded".to_string()])
  .build()
```

```rust
ButtonBuilder::new()
  .css_classes(["flat", "rounded"])
  .build()
```

Other Builders in `std` use the same pattern: see the documentation for https://doc.rust-lang.org/std/process/struct.Command.html#method.args

**Comment by bilelmoussaoui** [comment]
The issue is on the gir repository already

**Comment by ranfdev** [comment]
Indeed, I've found it: https://github.com/gtk-rs/gir/issues/1122.
Closing this then
