### ISSUE TITLE
[FEATURE REQUEST] gio::ListStore splice shouldn't allocate a Vec

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk-rs-core#423]
It's not necessary to map and collect a slice to a `Vec` of pointers. It can be casted.
Something like: `slice.as_ptr() as *const _ as *const *const glib::gobject_ffi::GObject`.

See #421 for some context

**Comment by sdroege** [comment]
I'm not 100% sure this is valid here because we have an `[impl IsA<Object>]`... but as that is only implemented for actual objects it should be safe.

If that's changed, I think your `Extend` impl can directly call this or not?

**Comment by ranfdev** [comment]
Nope... With the current API, `splice` needs to allocate always and `Extend` needs to allocate another time (if it calls `splice`) 

Explanation:
`ffi::g_list_store_splice` takes an array of pointers, then internally it increases the number of reference counts to the passed GObjects, so they will be kept in memory.

`splice` doesn't take an array of pointers. It takes a reference to an array of concrete GObjects.
Basically: `ffi::g_list_store_splice` wants a `C array of pointers` but `splice` takes an `array of concrete types`.
`splice` has to create that array of pointers, so it must allocate a `Vec`.

`Extend` has to create an allocation to transform an `IntoIterator` into a `Vec` (this can't be skipped in any case).
If `Extends` calls `splice`, 2 allocations happen.

BUT, changing the `splice` API to take a `&[&object]` instead of `&[object]` would solve "everything", since that's already an array of pointers.

**Comment by jf2048** [comment]
This probably needs some wrapper type like

```rust
struct UnownedObjectRef<'o> {
   inner: std::ptr::NonNull<gobject_ffi::GObject>,
   phantom: std::marker::PhantomData<&'o Object>,
}
```

**Comment by ranfdev** [comment]
In the end I've set `ListStore::splice` to do an unsafe cast:
`let additions = additions.as_ptr() as *mut *mut glib::gobject_ffi::GObject;`
and `Extend` to allocate a `Vec` and pass it to `ListStore::splice`.

See the related PR mentioned above for the implementation.
From my understanding `IsA<Object>` is equal to a `glib::gobject_ffi::GObject` so it's safe.
The code behind the `glib::Object` is full of macros, so I may have misinterpreted something and be wrong.
The simple test case I've added works.

**Comment by jf2048** [comment]
I mean to take `&[&object]`. I checked the PR and it does work, but requires `splice` taking ownership of the `ObjectRef`.

**Comment by sdroege** [comment]
What you described would work for keeping a reference but then you'd still need to collect such values into a `Vec`.

**Comment by jf2048** [comment]
I don't think `Vec` is needed if passing in a `&[T]`, as long as `T` is `repr(transparent)` to a C pointer?

**Comment by sdroege** [comment]
Ah sure, but then you need the user to create an `&[UnownedObjectRef]` somehow for the call.
