### ISSUE TITLE
Shouldn't upgrading an glib::WeakRef be thread safe?

### ISSUE THREAD

**Issue by jsparber** [gtk-rs/gtk-rs-core#426]
[`GWeakRef` ](https://docs.gtk.org/gobject/struct.WeakRef.html) says it's thread safe but in the binding we panic when trying to `upgrade()` a [glib::SendWeakRef](https://gtk-rs.org/gtk-rs-core/git/docs/glib/object/struct.SendWeakRef.html) from a thread different from the thread in which we created it. Shouldn't it also be thread safe in the rust world?

**Comment by sdroege** [comment]
No, why would it? `SendWeakRef` allows to send non-`Send` objects to other threads as long as you only ever upgrade it from the correct thread.

`WeakRef` also allows sending `Send` objects to other threads, but not non-`Send` objects.

**Comment by jsparber** [comment]
According to the docs is `g_weak_ref_get()` thread safe, which is the C function used in `upgrade()`

**Comment by jsparber** [comment]
ok nevermind. For some reason I though  `WeakRef` wasn't Send nor Sync.

**Comment by sdroege** [comment]
The problem is not `GWeakRef` but the object you're storing. It must be impossible to get a strong reference to a non-`Send` object from a different thread.
