### ISSUE TITLE
graphene: Generate NONE constants

### ISSUE THREAD

**Issue by A6GibKm** [gtk-rs/gtk-rs-core#447]
The none constants are not generated. e.g. `graphene::Rect::NONE`.

**Comment by sdroege** [comment]
There's no point in doing that, is there? All the graphene types don't have inheritance.

Where do you need it?

**Comment by A6GibKm** [comment]
gsk::Renderer::render_texture needs it.
```rust
        let renderer = gsk::CairoRenderer::new();
        renderer.realize(gdk::Surface::NONE).ok()?;
        paintable.snapshot_symbolic(&snapshot, SIZE.into(), SIZE.into(), &colors);
        let node = snapshot.to_node();
        let texture = renderer.render_texture(&node, None::<&graphene::Rect>);
```

**Comment by sdroege** [comment]
Just pass `None` there

**Comment by A6GibKm** [comment]
That fixes it, I wonder why the code I copied had it explicit. Thank
