### ISSUE TITLE
[BUG] emit_with_details arg validation fails

### ISSUE THREAD

**Issue by arcnmx** [gtk-rs/gtk-rs-core#460]
**Bug description**

Using glib 0.14, for a signal where `ObjectExt::emit` works, swapping it out with `ObjectExt::emit_with_details` produces the following error:

> BoolError { message: "Incompatible number of arguments for signal 'something' of type 'SimpleObject' (expected 1, got 2)", filename: "~/.config/cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.14.8/src/object.rs", function: "glib::object", line: 2318 }

This appears to be due to [emit_with_details](https://github.com/gtk-rs/gtk-rs-core/blob/c53f692d84f7f7a3a75362cd424427842f792e66/glib/src/object.rs#L2906) not skipping the `this` arg in the same way [emit does](https://github.com/gtk-rs/gtk-rs-core/blob/c53f692d84f7f7a3a75362cd424427842f792e66/glib/src/object.rs#L2815). [emit_with_details_and_values](https://github.com/gtk-rs/gtk-rs-core/blob/c53f692d84f7f7a3a75362cd424427842f792e66/glib/src/object.rs#L2967) is presumably also affected.

(sorry if I'm misunderstanding something and detailed signals are actually supposed to be different from unqualified ones in some way)

**Comment by sdroege** [comment]
Yes both functions are supposed to work the same way, this is indeed a bug.

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/461
