### ISSUE TITLE
[BUG] Quark is not optional or nullable

### ISSUE THREAD

**Issue by arcnmx** [gtk-rs/gtk-rs-core#462]
If a signal is called without details I'd expect `SignalInvocationHint::details()` to be `None`, but it's [not an optional type](https://docs.rs/glib/0.14.8/glib/subclass/signal/struct.SignalInvocationHint.html#method.detail). `glib::Quark` appears to not consider an empty quark as a valid value/state (though this isn't explicitly clear from the type/docs?), but it wraps `glib_sys::GQuark` which is nullable/zero'able. This might be a bug?

I might even suggest that `Quark` actually wrap a `NonZeroU32`, and impl `TryFromGlib<GQuark, Error=GlibNoneError>` instead; then `Option<Quark>` could be bit/repr/ffi-compatible with a `GQuark`, and the type would better represent the relationship between the sys and non-sys types?

EDIT: `glib::subclass::signal::SignalId::parse_name` has a similar issue, it returns a non-optional `Quark` which can cause a segfault:
```rust
println!("signal: {:?}", SignalId::parse_name("something", TestObject::static_type(), false));
793114 segmentation fault (core dumped)
```

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/464
