### ISSUE TITLE
Prevent all the copies in FFI translation by having Rust types for GLib arrays, strings, hash table, lists, etc

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#48]
See above. Those could implement all kinds of conversions to the actual Rust types, e.g. via Iterator::collect() for arrays, but use the GLib allocator for memory management.

These could be used for the "transfer full" return values (and out parameters) everywhere at least.

For "transfer none" we could at least automatically support 'static references. Non-static borrowing requires a lot of knowledge of the API and is better implemented manually.

**Comment by jf2048** [comment]
Currently have: `PtrSlice`, `Slice`, `PtrArray`, `List`, `SList`, `GString`

Still missing: `Array`, `HashTable`

**Comment by sdroege** [comment]
Also missing: making use of these from the code generator :)

> Still missing: `Array`, `HashTable`

These are hard (or impossible) to do right, see https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/305

**Comment by sdroege** [comment]
For arrays (including string arrays) and lists there are container types now. As mentioned above, the others are unfortunately hard to deal with and better handled by copying and on a case-by-case basis.
