### ISSUE TITLE
Cleanup the images

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs-core#484]
We should simplify the various images we use across gtk-rs here.

- Make a generic image that contains the building blocks in gtk-rs-core
- Inherit gtk3-rs/gtk4-rs from that image and only install the necessary stuff on top of it.

This would allow us to move to a common parent image (maybe fedora, or something else) and reduce the weird issues that could happen due to the differences between the base images

**Comment by jf2048** [comment]
Bumping to fedora latest will bring it up to glib 2.70: https://packages.fedoraproject.org/pkgs/glib2/glib2/fedora-35.html

It would probably be good to build the latest git for each package (glib, cairo, pango, gdk-pixbuf, graphene), but I can see a problem with this: In fedora, there is a circular dependency with `cairo-devel` -> `freetype-devel` -> `harfbuzz-devel` -> `cairo`

**Comment by bilelmoussaoui** [comment]
> Bumping to fedora latest

We could always use fedora rawhide for now that should give us glib 2.72 at least. We can figure try to figure out how to build glib ourselves in the future.

**Comment by jf2048** [comment]
This does seem to work correctly from git if using the meson subprojects and if built in the correct order

**Comment by bilelmoussaoui** [comment]
This is now done
