### ISSUE TITLE
IsA<_> can't be used for trait objects

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#49]
Reason for this is that the associated types of all super-traits have to be specified, i.e. `GlibType` of `Wrapper`, `Storage` of `ToGlibPtr`. By specifying those, using trait objects becomes useless as you already specified one specific type.

We should try to solve this, either by making those associated types generic types in one way or another, or otherwise untangling the traits. Not being able to use `IsA<_>` as a trait object is a big problem :)

Example compiler error when trying to use it as trait object:
```
error[E0191]: the value of the associated type `GlibType` (from the trait `glib::wrapper::Wrapper`) must be specified
  --> src/bin.rs:24:37
   |
24 |     fn add_many(&self, elements: &[&IsA<Element>]) -> Result<(), glib::BoolError> {
   |                                     ^^^^^^^^^^^^ missing associated type `GlibType` value

error[E0191]: the value of the associated type `Storage` (from the trait `glib::translate::ToGlibPtr`) must be specified
  --> src/bin.rs:24:37
   |
24 |     fn add_many(&self, elements: &[&IsA<Element>]) -> Result<(), glib::BoolError> {
   |                                     ^^^^^^^^^^^^ missing associated type `Storage` value
```

**Comment by sdroege** [comment]
As I noticed, everything implementing `IsA<T>` is also implementing `AsRef<T>` and `AsRef` is object-safe, so one can use `&dyn AsRef<T>` instead.

So there's not really any problem here anymore nowadays.

**Comment by kaixoo** [comment]
How other way is one supposed to check if `Button` or some other class is a `Widget` while retaining its `Widget` fields?

**Comment by sdroege** [comment]
You'd use a `gtk::Widget` and then cast accordingly. GObjects are basically behaving like trait objects, just without the Rust syntax sugar around them
