### ISSUE TITLE
Implement Downcast trait for Option<T>

### ISSUE THREAD

**Issue by JMS55** [gtk-rs/gtk-rs-core#497]
A lot of the time I do something like this:
```rust
widget.get_child().unwrap().downcast::<SomeWidget>().unwrap();
```
This gets to be really tedious and ugly. I propose gtk-rs should add a function equivalent to the above, something like:
```rust
widget.get_child_as::<SomeWidget>();
```

**Comment by bilelmoussaoui** [comment]
Fixed in https://github.com/gtk-rs/gtk-rs-core/pull/843
