### ISSUE TITLE
translate: trait TryFromGlib should be marked unsafe

### ISSUE THREAD

**Issue by fengalin** [gtk-rs/gtk-rs-core#5]
See https://github.com/gtk-rs/gtk-rs/pull/454#pullrequestreview-638331872

**Comment by sdroege** [comment]
@fengalin What should happen with this one?

**Comment by fengalin** [comment]
We didn't reach a conclusion in https://github.com/gtk-rs/gtk3-rs/pull/463. As an illustration, in `gstreamer-rs`, we have:

## `unsafe` `FromGlib`

```rust
impl FromGlib<ffi::GstBufferingMode> for BufferingMode {
    unsafe fn from_glib(value: ffi::GstBufferingMode) -> Self {
        [..]
    }
}
```

## Not `unsafe` `TryFromGlib`

```rust
impl TryFromGlib<ffi::GST_CLOCK_TIME_NONE> for CockTime {
    type Error = GlibNoneError;

    fn try_from_glib(v: ffi::GST_CLOCK_TIME_NONE) -> Result<Self, Self::Error> {
        [..]
    }
}
```

I think it would make sense to have both `unsafe` at least from a symmetry standpoint.

**Comment by sdroege** [comment]
Yes, I think the function at least should be `unsafe`. The main question is whether implementing the trait should be `unsafe` too. I.e. the difference between "the caller needs to make sure that things are ok" and "the implementer needs to make sure various properties are kept by the implementation".

**Comment by fengalin** [comment]
To me, we want to state that implementing this trait requires careful thinking in order to ensure everything is safe afterwards. So it would be more like:

> "the implementer needs to make sure various properties are kept by the implementation"

But it would probably also be the case for `FromGlib`.

**Comment by sdroege** [comment]
And also all the other translation traits, including the `To` ones or not?

**Comment by fengalin** [comment]
> And also all the other translation traits, including the To ones or not?

I guess so, but it would require further thinking from an audit of the main use cases. However, I don't have time to do this in the near future. What I would propose would be to keep the changes from https://github.com/gtk-rs/gtk3-rs/pull/463, this would be good enough for now.

**Comment by sdroege** [comment]
Yes, that would be consistent with `FromGlib` at least. Can you update the PR, then I'll merge it.

**Comment by fengalin** [comment]
> Can you update the PR, then I'll merge it.

Yes, it'll do that later today.

**Comment by fengalin** [comment]
Fixed with https://github.com/gtk-rs/gtk-rs-core/pull/84.
