### ISSUE TITLE
ToGlibPtrMove trait and "move" function parameter configuration

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#50]
It would be good to have a ToGlibPtrMove, that consumes the Rust wrapper struct and just returns the C pointer. Without any copying or change of reference count (if possible: e.g. for strings it is not).

In addition to that, a function parameter configuration to declare that parameter as "move" (i.e. using ↑, taking the Rust wrapper per value instead of as a reference) would be useful.

**Comment by GuillaumeGomez** [comment]
Now remains to add the gir parameter.

**Comment by bilelmoussaoui** [comment]
It would be nice to also implement `ToGlibPtrMove` for shared types as currently it is implemented for all the types generated with glib::wrapper! except shared ones.

**Comment by sdroege** [comment]
What's also missing is to do this automatically for non-refcounted types on `transfer full` parameters (and configurably for other types too, I guess: I want this for various refcounted types in GStreamer).

**Comment by sdroege** [comment]
> It would be nice to also implement `ToGlibPtrMove` for shared types as currently it is implemented for all the types generated with glib::wrapper! except shared ones.

See https://github.com/gtk-rs/gtk-rs-core/pull/756

**Comment by bilelmoussaoui** [comment]
Now that we have landed the automatically generated changes, the latest remaining step would be having a look at all the manual code and see where IntoGlibPtr could be used

**Comment by sdroege** [comment]
This has happened now.
