### ISSUE TITLE
[FEATURE REQUEST] Generic ToValue implementation for Vec<T>

### ISSUE THREAD

**Issue by hackel** [gtk-rs/gtk-rs-core#505]
Unless I'm doing something wrong, currently it is not possible to pass a new Vec into GObject::new because it doesn't implement glib::ToValue.  After some discussion in chat, it was suggested to create an issue for it.

e.g.
```rs
impl Conversation {
    pub fn new(groots: Vec<Groot>) -> Self {
        Object::new(&[("groots", &groots)])
            .expect("Failed to create `Conversation` model.")
    }
}
```
Error:
> `the trait bound std::vec::Vec<models::conversation::groot::Groot>: glib::ToValue is not satisfied the following implementations were found: <std::vec::Vecglib::GString as glib::ToValue> <std::vec::Vecstd::string::String as glib::ToValue> required for the cast to the object type dyn glib::ToValue`

See:
Conversation: https://play.rust-lang.org/?gist=94878262e1f51f24899ede9a8b475063
Groot: https://play.rust-lang.org/?gist=240a4990dcd4b470cdba92eef75e5713

**Comment by sdroege** [comment]
There is no pre-defined value type in GLib that is "an array with items of a specific type" unfortunately. You'll have to define your own wrapper around `Vec<Groot>` and derive a type for it via the `glib::Boxed` derive macro.

Or asked differently, what would you expect your code to expand to? Which GLib type should it use?

**Comment by sdroege** [comment]
Also your `groots` property only takes a single `Groot`, not multiple. So that wouldn't work anyway.

**Comment by sdroege** [comment]
What should we do about this one?

**Comment by bilelmoussaoui** [comment]
> There is no pre-defined value type in GLib that is "an array with items of a specific type" unfortunately. You'll have to define your own wrapper around Vec<Groot> and derive a type for it via the glib::Boxed derive macro.

Makes sense, I suppose the reason why there is a Vec<String> implementation is because there is some glib type that wraps that already?

**Comment by sdroege** [comment]
Yes, there's `G_TYPE_STRV` for string arrays.

**Comment by bilelmoussaoui** [comment]
Well, I guess we can close this. It would be nice to have some example on how to achieve something similar in the future.

**Comment by sdroege** [comment]
Personally I would go with a

```rust
#[derive(Clone, glib::Boxed)]
pub struct GrootVec(Vec<Groot>);
```

and then using `glib::ParamSpecBoxed` for the property.
