### ISSUE TITLE
[FEATURE REQUEST] Variant constructors are too statically typed

### ISSUE THREAD

**Issue by arcnmx** [gtk-rs/gtk-rs-core#507]
Certain types of variants are impossible to construct or work with using the public safe interface because they only take type parameters `T: StaticVariantType` rather than accepting a `ty: &VariantTy` argument:
- `Variant::array_from_iter` requires knowing the type in advance at compile-time to create an array of any kind.
- `Variant::from_maybe` has the same problem. It might make make more sense splitting it up into two apis:
  - `Variant::from_some(child: &Variant) -> Self`
  - `Variant::from_none(ty: &VariantTy) -> Self`
- Maybe variants have no equivalent to `variant.as_variant` - however this can at least be worked around using `variant.try_child_value(0)`
- `variant.is::<Ty>()` has no dynamic variant, and it's not clear whether comparison with `variant.type_()` or `is_subtype_of()` or similar would be equivalent?
- `Variant::from_bytes` / `from_data` serialization methods do actually have this via `Variant::from_X_with_type`!

Most of the above methods already panic if passed a value that doesn't match the expected type, so they do dynamic type checking anyway. One could argue that the way `T: StaticVariantType` is used is somewhat of an anti-pattern; a type parameter is being used in place of what otherwise should just be a normal argument, since it isn't even able to be inferred from other arguments it must always be explicitly provided. Sure, it saves you from typing `::static_variant_type()` (just use the `VariantTy::X` consts instead honestly), but it also hinders the usefulness of the API without maintaining duplicates of each method.
It might be nice if these methods actually used `T` as an argument type instead, for example constructing an array from a `IntoIterator<Item=T>`, but that gets messy... It might require a `DynamicVariantType + IntoVariant` set of traits in place of the existing `StaticVariantType + ToVariant` to allow them to still accept a plain `Variant` as an argument... and that wouldn't help when dealing with empty container types like `None` or an empty iter, complicates boxed variant types, and so on :<

Some of the above points may also apply to `Value` APIs as well, though it has a lot less surface area. `value.transform()` and `value.is()` look relevant at a glance?

cc @jf2048 who [has had to deal with this before](https://github.com/jf2048/glib-serde/blob/19e307a86786d385e655183c99212605e866d3dd/src/variant/mod.rs#L85-L97)

**Comment by sdroege** [comment]
I think adding more dynamically typed functions that take the type as argument (like already exist for other functions) and making use of the `T` where possible would make sense. Do you want to provide a PR for that?

> `variant.is::<Ty>()` has no dynamic variant, and it's not clear whether comparison with `variant.type_()` or `is_subtype_of()` or similar would be equivalent?

If you click on the `source` link that would be obvious but that should probably be documented at least.

> `Variant::from_maybe` has the same problem. It might make make more sense splitting it up into two apis:
> 
>     * `Variant::from_some(child: &Variant) -> Self`
> 
>     * `Variant::from_none(ty: &VariantTy) -> Self`

That sounds like a good idea to have in addition.

> It might be nice if these methods actually used T as an argument type instead, for example constructing an array from a IntoIterator<Item=T>, but that gets messy... It might require a DynamicVariantType + IntoVariant set of traits in place of the existing StaticVariantType + ToVariant to allow them to still accept a plain Variant as an argument... and that wouldn't help when dealing with empty container types like None or an empty iter, complicates boxed variant types, and so on :<

There could be a variant with `T` and another with `Variant`, so that doesn't seem much of a problem.

> Sure, it saves you from typing `::static_variant_type()` (just use the `VariantTy::X` consts instead honestly)

There is no constant for most complex types, but you can do `Option<Vec<(u8, String)>>::static_variant_type()` for example.

Personally I'm not using any of the APIs you mention directly but just go via Rust types and the traits implemented on them.

> Some of the above points may also apply to `Value` APIs as well, though it has a lot less surface area. `value.transform()`

Adding a variant of `transform()` like that seems useful, yes.

**Comment by arcnmx** [comment]
> and making use of the T where possible would make sense

I'll need to think more about this one, but I think it can be done reasonably with the existing design... For example, I think changing `array_from_iter` to take `IntoIterator<Item=T>` might be an improvement, and an `array_from_iter_with_type(&VariantTy, impl IntoIterator<Item=Variant>)` could just take the place of the existing function. This however will cause T to be inferred as `Variant` for existing code, resulting in a differently typed `av` than before, given the same arguments. However, currently any users are required to pass `T` explicitly because it can't be inferred from arguments or return type, so existing code would at least break with a type mismatch error rather than silently behaving differently.

> Do you want to provide a PR for that?

Sure.

> If you click on the source link that would be obvious but that should probably be documented at least.

That actually didn't help, because it's unclear to me whether `g_variant_is_of_type` implies strict equality or considers subtypes - I would assume the former but the `of` throws me off a little bit? This is presumably because I'm not familiar enough with glib's terminology; if I wanted to use this function in either a static or dynamic context, I wouldn't even know what I'm actually checking for! (so it's probably better to be explicit and just use `.type_()` as required anyway)... I honestly don't even know what subtype relationships are relevant when working with variants, or know intuitively an example of two types where `VariantTy::is_subtype_of` would return true. Or whether `Variant::get` can do conversions of any kind...

> There is no constant for most complex types, but you can do Option<Vec<(u8, String)>>::static_variant_type() for example.

Good point! Though I feel like if you're going for the util/helper/QOL angle, a `VariantType::with<X>()` approach could fill the gap.

> Personally I'm not using any of the APIs you mention directly but just go via Rust types and the traits implemented on them.

That's also kind of my point here. These APIs are pretty technical/low-level in that if you're working with them, you likely aren't going to benefit much from the "ease of use" associated with the `whatever::<X>` - if you already know the static types of the values you're working with, you're probably already using the traits like `ToVariant` directly on those values instead! It just kind of bloats the API by having multiple variants of each function, one of which is less flexible than the other.
(I'm not at all opposed to keeping them and just adding the new variants I've proposed, I just also think it's worth considering whether the originals are even worth keeping to begin with)

**Comment by sdroege** [comment]
> so existing code would at least break with a type mismatch error rather than silently behaving differently.

That seems acceptable to me

> I honestly don't even know what subtype relationships are relevant when working with variants

It only makes any difference compared to direct equality if the supertype is an abstract type (`a*`, `m*`, `r`, `{?*}` are the only abstract ones: array, maybe, tuple, dict entry with unspecified item types).

`t.is::<glib::VariantType::ARRAY>()` would be true for any kind of array, for example, but comparing both types for equality would give false.

> That's also kind of my point here.

That's a good point, yes. I'll have to think about that a bit :)

Adding new variants with a runtime parameter for providing the type seems completely fine to me in any case, just not entirely sure if the others should be dropped.

**Comment by arcnmx** [comment]
> t.is::<glib::VariantType::ARRAY>() would be true for any kind of array, for example, but comparing both types for equality would give false.

Okay, so it does include subtypes then, cool. Then my next question might be whether `VariantTy::is_subtype_of` is exclusive or not; does equality count as a subtype?

[glib docs say so explicitly](https://docs.gtk.org/glib/method.VariantType.is_subtype_of.html), but [this line is omitted from the rustdocs](https://gtk-rs.org/gtk-rs-core/git/docs/glib/struct.VariantTy.html#method.is_subtype_of) :(

I suppose it might be worth including in the docs for `Variant::is::<T>()` that this is basically just shorthand for `.type_().is_subtype_of()` then! That makes it more of a helper/util shorthand function that IMO doesn't need a second variant, since it can be written explicitly that way instead.

> > so existing code would at least break with a type mismatch error rather than silently behaving differently.
> 
> That seems acceptable to me

There's unfortunately one exception to this, though: imagine an existing use of this function for boxed variants:
```rust
let av = Variant::array_from_iter::<Variant, _>([Variant::from_variant(&5u32.to_variant())]);
```
Currently, this creates an `av` array of boxed variants. With the proposed change, this would silently double-box the values due to conversion via `T: StaticVariantType + ToVariant`. This is related to what I was hinting at in the OP where I mentioned an `IntoVariant`; we may want to take a page from `ToValue`, where `<Value as ToValue>::to_value` is a no-op (well, a clone) and an explicit `BoxedValue` type is used instead, this might be a fair bit more intuitive and consistent.

> That's a good point, yes. I'll have to think about that a bit :)

Oh I also forgot to add: if you need to reach for these functions to begin with, it's likely because you don't actually know the type statically in advance! Which is, y'know, why I ran into this issue to begin with :P

**Comment by sdroege** [comment]
> I do think it may be worth making them both behave consistently, and the current `Value` behaviour is more ergonomic and explicit imo.

I agree, yes.

> Oh I also forgot to add: if you need to reach for these functions to begin with, it's likely because you don't actually know the type statically in advance! Which is, y'know, why I ran into this issue to begin with :P

Probably true, yes. Let's go with that if @cgwalters and @lucab also agree (they added a few of those functions).

**Comment by cgwalters** [comment]
Can you give an example case you're trying to solve where you don't know the explicit variant type in advance?  I know there are some, I just want to be a bit clearer about what we're solving.

**Comment by arcnmx** [comment]
I specifically ran into this while working with wireplumber bindings; wp treats a `Variant` as a black-box untyped value for interop between config and plugins and scripts, sort of like what say `serde_json::Value` might be (lazily) used for in rust. These values may be constructed from user-configured JSON or other sloppily-typed data (lua tables are converted to/from variants), and must also be constructed in certain ways in order to pass them to other modules/scripts. While you often might know the type when working with serializing/deserializing explicit rust structs, it does get a bit messy/blurry when trying to process user-supplied data. The [example linked above](https://github.com/jf2048/glib-serde) ran into this need for similar reasons.
