### ISSUE TITLE
[FEATURE REQUEST] `g_value_{get,set}_pointer` is not exposed

### ISSUE THREAD

**Issue by arcnmx** [gtk-rs/gtk-rs-core#508]
The most obvious solution would come in the form of impl'ing `FromValue`/`ToValue` for `gpointer`/`gconstpointer`, though ideally probably as a blanket `*mut T`/`*const T`.

If there are concerns about memory safety... My assumption is that `GValue` doesn't care whether the pointer is valid or not, and thus it can be treated safely in the same way pointer types can be in rust. If any API accepts a `Value` containing a pointer with the intent of dereferencing it, I'd imagine it would need to be an unsafe API regardless of whether safe code can construct a pointer `Value` intentionally or not.

**Comment by sdroege** [comment]
There's also `g_pointer_type_register_static()` related to this btw. While what you suggest seems fine (but it unfortunately can't be a blanket implementation AFAICS, the compiler won't like that) some integration with that function would also be useful.

Having a PR to implement it around `*mut c_void` / `glib_sys::gpointer` for the time being seems fine though. Do you want to provide a PR for that?
