### ISSUE TITLE
Use a different type to indicate Pango Units

### ISSUE THREAD

**Issue by johncf** [gtk-rs/gtk-rs-core#53]
After looking at the [gir file](https://github.com/gtk-rs/gir-files/blob/master/Pango-1.0.gir), an automated way to generate this seems not possible. So, I would like to suggest two possible alternatives:

- Don't use gir! (How often does gir specs change?)
- Create a `Pango-1.0.gir.patch` file which would add special attributes to `Pango-1.0.gir` to handle cases like this and gtk-rs/pango#62. This will also involve adding pango-specific code-generation rules to [`gir`](https://github.com/gtk-rs/gir).

_Update:_ Below is an example implementation of pango units which would make working with them a lot more convinient and less error prone:
```rust
#[macro_use]
extern crate derive_more;

#[derive(Add, Sub, Mul, Div,
         AddAssign, SubAssign, MulAssign, DivAssign)]
struct Units(pub i32);

impl From<f64> for Units {
    fn from(val: f64) -> Units {
        Units((val * pango::SCALE as f64).round() as i32)
        // or use ffi::pango_units_from_double
    }
}

impl From<Units> for f64 {
    fn from(val: Units) -> f64 {
        val.0 as f64 / pango::SCALE as f64
        // or use ffi::pango_units_to_double
    }
}

```

**Comment by bilelmoussaoui** [comment]
It seems like there is an interest to completely drop this whole mess of Pango.Unit in Pango 2.0, maybe worth bringing the pain points upstream.

**Comment by bilelmoussaoui** [comment]
I will go ahead and close this one and let upstream fix it, it is too much of a change to do from the bindings side. Wdyt @sdroege ?

**Comment by sdroege** [comment]
Nobody seems to care enough to do the work, so yes let's close this. For GStreamer we did such things with `gst::ClockTime` but there was actual interest behind having this happen.
