### ISSUE TITLE
`cairo_surface_write_to_png_stream` is exposed only on `ImageSurface` without an obvious reason why 

### ISSUE THREAD

**Issue by RealKC** [gtk-rs/gtk-rs-core#541]
As far as I can tell, using cairo in C you'd be able to call `cairo_surface_write_to_png_stream` on any surface, but you'd have to check the returned status to see whether the surface actually supports this operation, at least this is how I interpret the following

> ### Returns
> [CAIRO_STATUS_SUCCESS](https://cairographics.org/manual/cairo-Error-handling.html#CAIRO-STATUS-SUCCESS:CAPS) if the PNG file was written successfully. Otherwise, [CAIRO_STATUS_NO_MEMORY](https://cairographics.org/manual/cairo-Error-handling.html#CAIRO-STATUS-NO-MEMORY:CAPS) is returned if memory could not be allocated for the operation, [CAIRO_STATUS_SURFACE_TYPE_MISMATCH](https://cairographics.org/manual/cairo-Error-handling.html#CAIRO-STATUS-SURFACE-TYPE-MISMATCH:CAPS) if the surface does not have pixel contents, or [CAIRO_STATUS_PNG_ERROR](https://cairographics.org/manual/cairo-Error-handling.html#CAIRO-STATUS-PNG-ERROR:CAPS) if libpng returned an error.

(src: https://cairographics.org/manual/cairo-PNG-Support.html#cairo-surface-write-to-png-stream)

**Comment by sdroege** [comment]
Yes that would work on any surface that can be converted to an image surface (which is probably most). Do you want to create a PR for making that API more generic?

**Comment by RealKC** [comment]
Sure that sounds fun, should I simply move the API to be on `Surface` (and add some docs for it) or is there a better way?

**Comment by sdroege** [comment]
That's what I would do, yes
