### ISSUE TITLE
[FEATURE REQUEST] Add method to register types

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gtk-rs-core#542]
Most apps currently call `static_type` within `class_init` to register custom widgets they refer to within the composite template.
That is not a nice way to do it, since we are not interested in the returned type, but rather it's side effect: registering the type.
It would be good to have a method which does only that.
It could be named `type_ensure` corresponding to the function `g_type_ensure`.
Maybe `register_type` would work as well?

@bilelmoussaoui @sdroege

**Comment by Hofer-Julian** [comment]
> Makes sense but where would you put that function for it to be least confusing? glib::Type::ensure_type::<T: StaticType>()

That sounds okay I think (with `type_ensure` instead of `ensure_type` to stay consistent with the C API.
Ideally it would be a method like `CustomWidget::type_ensure()`, but I guess that would have to be added within `gir`

> It doesn't register the type though, only on the first call.

Okay? The [docs](https://docs.gtk.org/gobject/func.type_ensure.html) made it sound to me as if this function would register the type if it isn't already.

> Ensures that the indicated type has been registered with the type system, and its _class_init() method has been run.

**Comment by sdroege** [comment]
> Not necessarily, it can be add to the StaticType trait :-)

Yes, with a default implementation. Or even better as a `StaticTypeExt` trait that has a blanket implementation (this would prevent implementors to implement that function wrongly).

> Okay? The [docs](https://docs.gtk.org/gobject/func.type_ensure.html) made it sound to me as if this function would register the type if it isn't already.

Yes, that's what I said. It doesn't register the type on every call again.

**Comment by Hofer-Julian** [comment]
> Yes, with a default implementation. Or even better as a StaticTypeExt trait that has a blanket implementation (this would prevent implementors to implement that function wrongly).

Nice :)

> Yes, that's what I said. It doesn't register the type on every call again.

Fair enough.
Then I guess `type_ensure` is indeed a better name.

**Comment by Hofer-Julian** [comment]
@bilelmoussaoui

**Comment by sdroege** [comment]
Seems fine to me. Want to send a PR?
