### ISSUE TITLE
Support for dynamic types

### ISSUE THREAD

**Issue by shutton** [gtk-rs/gtk-rs-core#55]
glib_wrapper! doesn't appear to have any support for dynamic types (types that become available after being loaded from a dynamic library)

https://developer.gnome.org/gobject/2.64/GTypeModule.html#G-DEFINE-DYNAMIC-TYPE:CAPS

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/1169
