### ISSUE TITLE
Fix cairo FFI types name

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gtk-rs-core#550]
A lot of cairo FFI types are misnamed (I discovered it while working on https://github.com/gtk-rs/gtk-rs-core/pull/549). It'd be better to use the "real" names instead.

**Comment by sdroege** [comment]
Misnamed in what sense?

**Comment by bilelmoussaoui** [comment]
For example `cairo_matrix_t` is named `Matrix`

**Comment by sdroege** [comment]
Yes but @GuillaumeGomez fixed that already in https://github.com/gtk-rs/gtk-rs-core/pull/549

**Comment by bilelmoussaoui** [comment]
There might be others, I noticed one a couple of months ago, it could have been Matrix. Worth investigating

**Comment by GuillaumeGomez** [comment]
There are others, hence why I opened this issue. Will very likely go through it today.
