### ISSUE TITLE
[FEATURE REQUEST] Move `gio::compile_resources` to a seperate crate

### ISSUE THREAD

**Issue by JMS55** [gtk-rs/gtk-rs-core#574]
Currently my build script exists just to run this function, and that requires depending on the entirety of glib and gio for the build script (build scripts do _not_ share dependencies with the rest of your project). Additionally, it doesn't really make sense to need to update the gio version for the build script to keep in sync with your project's gio, when nothing with this one function changed.

I think it would make sense to split this into a separate crate. As far as I can tell, the function doesn't depend on anything from glib/gio, just the rust stdlib.

**Comment by jf2048** [comment]
Maybe it should go in a gio-macros package? There was another PR open for that.

**Comment by jf2048** [comment]
For some reason I thought it was a macro, I just realized it is an ordinary function

**Comment by ids1024** [comment]
It would be nicer as a proc macro, but as far as I'm aware reading from files in proc macros is currently considered a hack and the correct way is to do this is in `build.rs`.
