### ISSUE TITLE
[FEATURE REQUEST] impl `ToValue` for char

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk-rs-core#576]

**Comment by sdroege** [comment]
To which C API / `GType` should that map?

**Comment by ranfdev** [comment]
`glib::translate::IntoGlib` maps `char` to `u32`. I think `u32` in glib is `uint`

**Comment by sdroege** [comment]
That could make sense, also in the other direction (but not every `u32` is a valid `char` so some checks are needed). At the `GType` level however there is no distinction between `u32` and `char` then, which might be problematic / ugly.

@GuillaumeGomez @bilelmoussaoui Opinions?

**Comment by GuillaumeGomez** [comment]
Not really. If it allows to improve the quality of our bindings, I'm all for it.
