### ISSUE TITLE
[BUG] Cairo show font to pdf in windows. some character gone

### ISSUE THREAD

**Issue by lencil** [gtk-rs/gtk-rs-core#590]
the original function,

`void cairo_show_text(cairo_t *cr, const char *utf8)`, not a c char, but a utf8 array
and cairo_show_glyphs()
cairo_scaled_font_text_to_glyphs() etc.

but in rust bind code
```
    #[doc(alias = "cairo_show_text")]
    pub fn show_text(&self, text: &str) -> Result<(), Error> {
        unsafe {
            let text = CString::new(text).unwrap();
            ffi::cairo_show_text(self.0.as_ptr(), text.as_ptr())
        };
        self.status()
    }

    #[doc(alias = "cairo_show_glyphs")]
    pub fn show_glyphs(&self, glyphs: &[Glyph]) -> Result<(), Error> {
        unsafe { ffi::cairo_show_glyphs(self.0.as_ptr(), glyphs.as_ptr(), glyphs.len() as c_int) };
        self.status()
    }
```
convert &str to CString, and passed an standard c char*, not utf8 buffer array this will lead some issue in windows with CJK fonts.

I just approach the problem by convert to c_utf8 array
```
            let c_str = CString::new(String::from(c).as_str()).unwrap();
            let c_utf8 = c_utf8::CUtf8::from_c_str(c_str.as_c_str()).unwrap();
            if let Ok((glyphs, clusters)) = scaled_font.text_to_glyphs(x, y, c_utf8.as_str()) {
                // if index == 0 , then glyph not exist
                if glyphs[0].index > 0 {
                    return Some((glyphs, clusters));
                }
            }
```

**Comment by sdroege** [comment]
I'm not sure what exactly the problem here is. Rust strings are guaranteed to be valid UTF-8 and `CString` adds the `\0`-terminator to the end. Any `char *` strings in cairo (except for filenames/paths) are required to be / guaranteed to be valid UTF-8 and `\0`-terminated.

**Comment by sdroege** [comment]
Can you maybe provide a minimal testcase for something that fails and explain how it fails?

**Comment by lencil** [comment]
ok, only on windows, with CJK strings. In windows, the char* may not always utf8 array. I'll upload a sample later.

**Comment by sdroege** [comment]
Why would it not always be UTF-8, in which API? From the Rust side, all strings would always be UTF-8 but also the `c_utf8` crate assumes every string that goes over FFI is UTF-8.

This sounds to me like somewhere something else is broken or wrong. Waiting for the sample and explanation what exactly is passed where that causes things to break. Maybe it's a bug in cairo :)

**Comment by lencil** [comment]
try this demo.
[cairo_font.zip](https://github.com/gtk-rs/gtk-rs-core/files/8207425/cairo_font.zip)

how to reproduct:

install font FZSTK.TTF that's in the source code root into windows system.

install vcpkg in windows
https://github.com/microsoft/vcpkg

and install cairo lib
vcpkg install cairo --triplet x64-windows

set environment var
SET PKG_CONFIG_PATH=[vcpkg root]/installed/x64-windows/lib/pkgconfig

cargo run --release

output.png and output.pdf will generated.

the output.png is right, but the output.pdf is wrong. some character gone.

**Comment by lencil** [comment]
only in windows, in linux, work fine.
the result:
![output](https://user-images.githubusercontent.com/9926721/157270620-0cd1dadb-e6a9-4360-8be2-5d5c26d2dd5b.png)
[output.pdf](https://github.com/gtk-rs/gtk-rs-core/files/8207478/output.pdf)
t

**Comment by sdroege** [comment]
And the change with `c_utf8` from the first comment actually makes this work for you? I would expect that to behave exactly the same.

**Comment by lencil** [comment]
> And the change with `c_utf8` from the first comment actually makes this work for you? I would expect that to behave exactly the same.
not utf8 issue. I found that it's behave the same after I try again.

the pdf issue only occured when set slant to italic and weight bold.

**Comment by sdroege** [comment]
Considering that the very same code works for PNG but not PDF, I'd consider this a bug somewhere inside cairo. There's nothing on the bindings side that could break this in such a way.

Can you report it to https://gitlab.freedesktop.org/cairo/cairo/-/issues/new ?
