### ISSUE TITLE
gobject-sys: license file missing from published crates

### ISSUE THREAD

**Issue by decathorpe** [gtk-rs/gtk-rs-core#594]
Looks like https://github.com/gtk-rs/gtk-rs-core/issues/172 was not fixed entirely.
The published gobject-sys crates still do not contain a license file as of 0.15.7.

**Comment by sdroege** [comment]
This only affects gobject-sys, correct? That one is missing the symlink to the license file, the others seem to have it unless I missed one.

**Comment by decathorpe** [comment]
Yes, I think gobject-sys was the only one that was missed. Thanks!

**Comment by sdroege** [comment]
0.15.9 has it now
