### ISSUE TITLE
[BUG] pango::GlyphItemIter is unsound

### ISSUE THREAD

**Issue by jf2048** [gtk-rs/gtk-rs-core#610]
**Bug description**

The struct holds a borrowed pointer to the `GlyphItem`. It needs to have a lifetime parameter scoped to the `GlyphItem`. Minimal crash reproducer:

```rust
fn main() {
    const LOREM: &str = "\
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor \
incididunt ut labore et dolore magna aliqua. Ut enim ad sapientiam perveniri \
potest, non paranda nobis solum ea, sed fruenda etiam sapientia est; sive hoc \
difficile est.";

    use pango::prelude::*;

    let mut iter = {
        let map = pangocairo::FontMap::default().unwrap();
        let pc = map.create_context().unwrap();
        let layout = pango::Layout::new(&pc);
        layout.set_width(256 * pango::SCALE);
        layout.set_height(256 * pango::SCALE);
        layout.set_text(LOREM);
        let mut layout_iter = layout.iter().unwrap();
        let item = layout_iter.run().unwrap();
        pango::GlyphItemIter::new_start(&item, LOREM).unwrap()
    };
    loop {
        println!(
            "{} {} {} {} {} {}",
            iter.start_glyph(), iter.start_index(), iter.start_char(),
            iter.end_glyph(), iter.end_index(), iter.end_char(),
        );
        if !iter.next_cluster() {
            break;
        }
    }
}
```

**Backtrace**

```
Stack trace of thread 2735378:
#0  0x00007fb484e15e0e pango_glyph_item_iter_next_cluster (libpango-1.0.so.0 + 0x28e0e)
#1  0x00005612ab9df66e n/a (pangotest + 0x2866e)
```

**Comment by jf2048** [comment]
`AttrIterator` looks like it has the same problem

**Comment by bilelmoussaoui** [comment]
Probably worth looking at other *Iter types as well

**Comment by jf2048** [comment]
In order to make this work, `glib::wrapper!` probably needs to somehow gain support for lifetimes and `PhantomData` fields

**Comment by bilelmoussaoui** [comment]
or we can manually implement them similar to BitsetIter in gtk4

**Comment by jf2048** [comment]
Sure, and then just get rid of the `Value` traits. It is unsafe to put this in a `Value` anyway because those have to be `'static`

**Comment by sdroege** [comment]
`glib::wrapper!` already has support for lifetimes etc :)

**Comment by jf2048** [comment]
It seems because it uses `$generic:ident`, that only supports type parameters. It would need to use something else like `$generic_lt:lifetime` to support lifetimes. Also, the pattern for `Boxed(...)`, `BoxedInline(...)`, etc does not support adding extra fields to the struct.
