### ISSUE TITLE
[BUG] Convert a GVariant to OsString adds a NUL byte

### ISSUE THREAD

**Issue by rodrigorc** [gtk-rs/gtk-rs-core#620]
**Bug description**

I'm trying to use `gtk::Application::connect_handle_local_options` to add an option to open a file. Converting the `GVariant` to a `std::string` works fine, but if I try the properer way of setting `glib::OptionArg::Filename` and getting a `std::ffi::OsString` or a `std::path::PathBuf`, it gets an extra NUL byte at the end.

```
use gtk::prelude::*;

fn main() {
    let app = gtk::Application::new(None,
        gio::ApplicationFlags::HANDLES_OPEN | gio::ApplicationFlags::NON_UNIQUE
    );
    app.add_main_option("import", glib::Char::from(b'I'),
        glib::OptionFlags::NONE, glib::OptionArg::Filename,
        "Imports a file", None);
    app.connect_handle_local_options(
        move |_app, dict| {
            let s: Option<std::ffi::OsString> = dict.lookup("import").unwrap();
            if let Some(s) = s {
               std::fs::read(dbg!(s)).unwrap(); // Panics!
            }
            -1
        }
    );
    app.run();
}
```
Run it with `cargo run -- --import foo`:
```
[src/main.rs:12] s = "foo\u{0}"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidInput, message: "data provided contains a nul byte" }', src/main.rs:12:39
```

I'm not sure if it is a bug in glib itself, because maybe it should not add the NUL to the GVariant in the first place, or a bug in the Rust binding. In C that NUL byte is invisible so not a big deal, but in Rust Rust it makes my program crash and it is not so easy to remove.

**Comment by sdroege** [comment]
That's an interesting problem. As these are just byte arrays but in a `Variant` the length is known and a `NUL` terminator is not really needed, it would be GLib adding it here. For C compatibility reasons, I assume.

I think the `glib` bindings should skip the terminating `NUL` for `OsString` when deserializing from a `Variant`. [Here](https://gtk-rs.org/gtk-rs-core/git/docs/src/glib/variant.rs.html#1774-1779) and [here](https://gtk-rs.org/gtk-rs-core/git/docs/src/glib/variant.rs.html#1786-1791).

Do you want to provide a PR for that?

CC @euclio
