### ISSUE TITLE
glib: Internal error checking in closures and signal handlers should abort instead of panic

### ISSUE THREAD

**Issue by jf2048** [gtk-rs/gtk-rs-core#645]
This is in places such as inside the callbacks in `RustClosure` and `ObjectExt::try_connect_unsafe_id`. A user will never be able to safely use `catch_unwind` on these because they always cross an FFI boundary.

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/issues/74 . This will be solved once `C-unwind` is stabilized AFAIU
