### ISSUE TITLE
[BUG] cairo-rs context.paint() or fill() not working

### ISSUE THREAD

**Issue by wanming** [gtk-rs/gtk-rs-core#661]
**Bug description**

context.paint() or fill() not work on alpine linux, the backgroud of the output png is transparent. 

but it works fine on macOS or debian.

**How to reproduce**

download my example code zip, unzip it, and run `cd cairo-issue`:

[cairo-issue.zip](https://github.com/gtk-rs/gtk-rs-core/files/8560987/cairo-issue.zip)

```bash
docker run -v $PWD:$PWD -it -w $PWD rust:1.60.0-alpine3.15 /bin/sh
```

in docker shell:

```bash
apk add cairo-dev libc6-compat musl-dev
cargo run
```

check the output.png in code folder, the background of the output png should be yellow. but it's not.

I'v tried install other packages, like gtk+3.0-dev or gtk4.0-dev, but the results are the same.

appreciate it if you can give me some help, thanks.

**Comment by sdroege** [comment]
That sounds like something to report to https://gitlab.freedesktop.org/cairo/

**Comment by wanming** [comment]
I tried to run c code on alpine linux, it works fine, the backgroud shows correctly. 

So I think it may be a bug of cairo-rs, I'm not sure, here is my c code:

```c
#include <cairo.h>

int main(void)
{
  cairo_surface_t *surface;
  cairo_t *cr;

  surface = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, 390, 60);
  cr = cairo_create(surface);

  cairo_set_source_rgb(cr, 0.0, 1.0, 1.0);
  cairo_paint(cr);

  cairo_surface_write_to_png(surface, "image.png");

  return 0;
}

// gcc t.c -o example `pkg-config --cflags --libs cairo`
```

**Comment by sdroege** [comment]
> ```c
>   surface = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, 390, 60);
> ```

You Rust code uses 100x100

> ```c
>   cairo_set_source_rgb(cr, 0.0, 1.0, 1.0);
> ```

Your Rust code uses `1.0 1.0 0.1`

If you change them to the same they still behave differently? Are both the C and Rust version linked to the same version of cairo (check with `ldd`)?

The Rust code is literally just calling those C functions :)

**Comment by sdroege** [comment]
My best guess would be that it's some miscompilation of cairo or so on alpine, or because of alpine using musl

**Comment by psychon** [comment]
For the sake of whoever comes across this and wants to find the corresponding cairo issue: https://gitlab.freedesktop.org/cairo/cairo/-/issues/564

**Comment by wanming** [comment]
I finally found out that it should be a problem with rust compilation. It finally works fine after I add an ENV RUSTFLAGS=-Ctarget-feature=-crt-static before cargo build, which means compiling rust code on 'dynamic link' mode(default is static-link, but it's meaningless because I have already used Cairo dynamic link). there should be some bug or strange behavior in rust compilation, I guess.
thanks/sorry for taking your time.

**Comment by sdroege** [comment]
There's various strangenesses with musl that require such things, yes. See for example https://github.com/rust-lang/rust/issues/82193 , https://github.com/gtk-rs/gtk-rs-core/issues/387#issuecomment-976857833, https://github.com/rust-lang/compiler-team/issues/422
