### ISSUE TITLE
[FEATURE REQUEST] Add method like connect_destroy to `ObjectExt`

### ISSUE THREAD

**Issue by AaronErhardt** [gtk-rs/gtk-rs-core#662]
It seems like it is possible to use [`ObjectExt::watch_closure()`](https://gtk-rs.org/gtk-rs-core/git/docs/glib/object/trait.ObjectExt.html#tymethod.watch_closure) together with a `Drop` implementation to create a callback similar to [`WidgetExt::connect_destroy()`](https://gtk-rs.org/gtk4-rs/git/docs/gtk4/prelude/trait.WidgetExt.html#tymethod.connect_destroy).

I wonder if this could be added to `ObjectExt` (or somewhere else) as a method similar to `connect_destroy` to make it easier to find and to use. Potentially there is even a simpler method to archive this callback.

For reference: https://github.com/Relm4/Relm4/pull/152#issuecomment-1083086071

**Comment by sdroege** [comment]
Something like https://github.com/gtk-rs/gtk-rs-core/pull/429 ?

**Comment by AaronErhardt** [comment]
Yes, that'd be pretty much what I want, just more idiomatic I think. I only wonder whether the name is a bit misleading because weak references are not what determines the lifetime of an object and are just the mechanism behind this implementation.

**Comment by sdroege** [comment]
It's how the C API is called :) Please comment on that PR with any suggestions

**Comment by jf2048** [comment]
Is this closed by #666?
