### ISSUE TITLE
[BUG] glib::BindingGroup bindings are broken

### ISSUE THREAD

**Issue by A6GibKm** [gtk-rs/gtk-rs-core#664]
The following operation crashes
```rust
        let binding_group = glib::BindingGroup::new();
        binding_group
            .bind("some_prop", &some_target_object, "other_prop")
            .build();

        binding_group.set_source(Some(&source_object));
```

with message  [(full backtrace)](https://gitlab.gnome.org/-/snippets/3411)
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "Binding group does not have a source set"...
```
But the binding groups are meant to be used without a source object. The bindings are connected and disconnected whenever a new source object is set.

The other problem is that in C, the bindings are by default have G_BINDING_BIDIRECTIONAL by default.

The expected behavior is stated in the [docs](https://docs.gtk.org/gobject/class.BindingGroup.html) and can be verified to work as advertised.

**Comment by sdroege** [comment]
CC @jf2048

**Comment by jf2048** [comment]
It sounds good to me to have the flags in `BindingGroupBuilder` set to `BIDIRECTIONAL` by default

**Comment by jf2048** [comment]
If the test is doing the same thing that C is doing, then it seems you would verify that the flag is needed?
