### ISSUE TITLE
cairo: Is it okay to migrate freetype to freetype-rs or use freetype-sys directly?

### ISSUE THREAD

**Issue by songww** [gtk-rs/gtk-rs-core#693]

**Comment by sdroege** [comment]
What would be the rationale for this? We can change to whatever makes more sense :)

**Comment by songww** [comment]
The freetype bindings has not been updated for 5 years and do not contain secure bindings.
The crate that contains safe bindings is freetype-rs, which has been actively maintained, but is not compatible with freetype.

Sorry my english is poor.

**Comment by sdroege** [comment]
> The freetype bindings has not been updated for 5 years and do not contain secure bindings.
> The crate that contains safe bindings is freetype-rs, which has been actively maintained, but is not compatible with freetype.

Thanks, that perfectly makes sense. Do you want to provide a PR for that?

> Sorry my english is poor.

Don't worry, your English seems perfectly fine to me :)

**Comment by sdroege** [comment]
Thanks for remembering to close this issue
