### ISSUE TITLE
Consider to change the default behaviour of `run`

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gtk-rs-core#697]
The method [`run`](https://gtk-rs.org/gtk-rs-core/stable/0.15/docs/gio/prelude/trait.ApplicationExtManual.html#tymethod.run) captures the command line arguments.

This behaviour results in confusion on a regular basis (see e.g. https://github.com/gtk-rs/gtk4-rs/issues/1039).
I propose to stop capturing the command line arguments in `run` and require users to capture the arguments themselves and pass them to `run_with_args`.

**Comment by sdroege** [comment]
Well that's how it was until a year ago: https://github.com/gtk-rs/gtk-rs-core/commit/e49d8f6768bd763acfcb9a2343b5f792a7104a7d

People were complaining about the exact opposite of what you're saying now. So what should we do? :)

**Comment by sdroege** [comment]
PR for this was https://github.com/gtk-rs/gtk3-rs/pull/421

CC @pbor @bilelmoussaoui @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
We should provide a `run_no_capture` so everyone is happy. :laughing:

**Comment by Hofer-Julian** [comment]
> We should provide a `run_no_capture` so everyone is happy. 😆

I think the main problem is that people find it hard to figure out why they get an error message when running their apps with arguments. So that wouldn’t help much.

**Comment by bilelmoussaoui** [comment]
The amount of people that have to parse the arguments manually instead of going through glib is pretty low. So I would rather keep the situation as is.

**Comment by sdroege** [comment]
The current situation is also closer to how the Python and GJS bindings work. What is different there that doesn't make this a problem for people?

**Comment by Hofer-Julian** [comment]
> The current situation is also closer to how the Python and GJS bindings work. What is different there that doesn't make this a problem for people?

Good question, I don't have much experience there. 
Do you interact with those communities enough to know that it makes no problems there?

Maybe it could be improved by choosing better names for the methods: people might be confused that `run_with_args` is the one you use if you don't want argparsing be handled automatically.
And/or better doc visibility: on gtk4-rs' docs neither `run` nor `run_with_args` display any [docs](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/struct.Application.html#method.run).
You have [docs](https://gtk-rs.org/gtk-rs-core/stable/0.15/docs/gio/prelude/trait.ApplicationExtManual.html#tymethod.run) on gio but they only make little sense for our bindings.

**Comment by bilelmoussaoui** [comment]
> Do you interact with those communities enough to know that it makes no problems there?

I am in both gjs/pygobject Matrix channels and haven't seen much complaints about this.

**Comment by sdroege** [comment]
So let's close this then?

**Comment by Hofer-Julian** [comment]
Yes, I would say so
