### ISSUE TITLE
BindingGroup: Does not allow mapping between properties of different types

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#700]
See https://github.com/gtk-rs/gtk-rs-core/pull/665#discussion_r872075043

**Comment by sdroege** [comment]
Actually working fine. I made a PR that adds some tests.

@A6GibKm I assume your problem was that you didn't add a `transform_to` function but created the binding with `SYNC_CREATE`. During binding creation you then need something to do the conversion also in the other direction.

**Comment by A6GibKm** [comment]
Great to know, thanks!
