### ISSUE TITLE
[FEATURE REQUEST] Borrow on Object types

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk-rs-core#711]
An object subclass already implements `AsRef<$ParentObject>`. Could it also implement `Borrow<$ParentObject>`?

The Borrow trait has different requirements and I don't know if this is possible.
From the rust doc:
> AsRef has the same signature as [Borrow](https://doc.rust-lang.org/std/borrow/trait.Borrow.html), but [Borrow](https://doc.rust-lang.org/std/borrow/trait.Borrow.html) is different in few aspects:
    - Unlike AsRef, [Borrow](https://doc.rust-lang.org/std/borrow/trait.Borrow.html) has a blanket impl for any T, and can be used to accept either a reference or a value.
    - [Borrow](https://doc.rust-lang.org/std/borrow/trait.Borrow.html) also requires that [Hash](https://doc.rust-lang.org/std/hash/trait.Hash.html), [Eq](https://doc.rust-lang.org/std/cmp/trait.Eq.html) and [Ord](https://doc.rust-lang.org/std/cmp/trait.Ord.html) for borrowed value are equivalent to those of the owned value. For this reason, if you want to borrow only a single field of a struct you can implement AsRef, but not [Borrow](https://doc.rust-lang.org/std/borrow/trait.Borrow.html).
    
I would use the `Borrow` trait to accept parameters in setter functions in the Properties macro (#494). `AsRef` isn't enough because it doesn't have a blanket impl for any T

**Comment by sdroege** [comment]
`Borrow` seems semantically the wrong trait for subtyping, and it also has the connections to the `ToOwned` trait which doesn't fit at all here.

Why do you need `Borrow`?

**Comment by ranfdev** [comment]
Let's say I have a struct with two fields: 
```rust
#[derive(Properties)
struct MyClass {
  mystring: RefCell<String>,
  myobject: RefCell<Object>,
}
```
and given the related traits:

```rust
impl HasParamSpec for String {
    type ParamSpec = ParamSpecString;
    type SetValue = str;
}
impl HasParamSpec for Object {
    type ParamSpec = ParamSpecString;
    type SetValue = Object; // Ideally this would be a generic associated type `IsA<Object>`, but rust can't do that yet.
}
```

the related setter functions are
```rust
pub fn set_mystring(&self, value: HasParamSpec::SetValue);
pub fn set_myobject(&self, value: HasParamSpec::SetValue);  // This won't accept subclasses, until rust has GATs 
``` 

Until we have GATs in rust, we could have
```rust
pub fn set_mystring(&self, value: Borrow<HasParamSpec::SetValue>);
pub fn set_myobject(&self, value: Borrow<HasParamSpec::SetValue>);  // This could accept subclasses if Borrow<ParentClass> is implemented
``` 

`Borrow` has a blanket implementation for any T, so it works well even with other types as `f64`, `f32`... `AsRef` isn't implemented on floats (and other types), so I can't use that.

**Comment by jf2048** [comment]
I think it is actually possible to hack this using autoderef specialization to generate a setter method that detects if something implements `IsA<Object>`

**Comment by jf2048** [comment]
I don't understand how this is supposed to work, you would have to implement it for `T: IsA<Object>`, not for each object type
