### ISSUE TITLE
[FEATURE REQUEST] pango::extents_to_pixels should take mutable references

### ISSUE THREAD

**Issue by ArchitBhonsle** [gtk-rs/gtk-rs-core#727]
Although it should [clearly](https://docs.gtk.org/Pango/func.extents_to_pixels.html) take exclusive references, [`extents_to_pixels`](https://docs.gtk.org/Pango/func.extents_to_pixels.html) takes shared references.

**Comment by sdroege** [comment]
This was broken in e7a4efa0eb35

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/730
