### ISSUE TITLE
`glib::closure!` macro and signal connector should use more descriptive assertions

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#729]
E.g. currently when the number of arguments does not match one simply gets an assertion that e.g. `2 != 5` without any hints about the actual problem.

CC @jf2048 @bilelmoussaoui

**Comment by jf2048** [comment]
I think we can try with another shot at this one again: https://github.com/gtk-rs/gtk-rs-core/pull/567 now that it is looking like GATs will make it into Rust 1.65?

**Comment by sdroege** [comment]
Yeah worth trying again with 1.65 :) Not sure if there's enough GAT to make it work though.
