### ISSUE TITLE
[BUG] `set_user_data` might have a memory leak if the function errors

### ISSUE THREAD

**Issue by SabrinaJewson** [gtk-rs/gtk-rs-core#740]
**Bug description**

[In `set_user_data`](https://github.com/gtk-rs/gtk-rs-core/blob/faed1d691ecc513d13869d20bf0a26c4f0a8fd54/cairo/src/user_data.rs#L61), if the function `$ffi_set_user_data` were to fail I don’t believe Cairo will ever run the destructor, so therefore there would be a memory leak of the `Rc` (the [example code for `cairo_ft_font_face_create_for_ft_face`](https://www.cairographics.org/manual/cairo-FreeType-Fonts.html#cairo-ft-font-face-create-for-ft-face) seems to imply this). To fix this I believe it just needs to check if an error occurred and if so call `destructor(ptr)`. However, I’m not certain about this so I’m only opening an issue and not a pull request.

**Comment by sdroege** [comment]
You're probably right but this is not very clear from the docs unfortunately. Needs some checking of the actual implementation.

Note that AFAIU this function can only fail when running out of memory.

**Comment by sdroege** [comment]
Yes, in all error cases the data would be leaked.

@SabrinaJewson Do you want to submit a PR that fixes this leak?

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/745

**Comment by SabrinaJewson** [comment]
Thank you for handling this! I was away from my computer for a couple days.
