### ISSUE TITLE
[BUG] Failed to get `i32` from a variant of type `h`

### ISSUE THREAD

**Issue by SeaDve** [gtk-rs/gtk-rs-core#747]
**Bug description**

Minimal reproducer:
```
let handle_variant = glib::Variant::parse(None, "handle 0").unwrap();
dbg!(&handle_variant);
dbg!(handle_variant.get::<i32>());
dbg!(handle_variant.get::<std::os::unix::prelude::RawFd>());
```
output:
```
[src/main.rs:50] &handle_variant = Variant {
    ptr: 0x0000556c6700bc30,
    type: VariantTy {
        inner: "h",
    },
    value: "handle 0",
}
[src/main.rs:51] handle_variant.get::<i32>() = None
[src/main.rs:52] handle_variant.get::<std::os::unix::prelude::RawFd>() = None
```

**Comment by sdroege** [comment]
It's because `i32` is both `i` and `h` and we currently only handle `i`. This probably needs a `pub struct VariantHandle(pub i32)` wrapper type to distinguish these cases properly.

**Comment by SeaDve** [comment]
Maybe this could be handled similar to `o`, `s`, & `g` and `String`

**Comment by sdroege** [comment]
In what sense?

**Comment by SeaDve** [comment]
Both
```
    dbg!(
        glib::Variant::parse(Some(glib::VariantTy::new("o").unwrap()), "'/foo'")
            .unwrap()
            .get::<String>()
    );
    dbg!(
        glib::Variant::parse(Some(glib::VariantTy::new("s").unwrap()), "'bar'")
            .unwrap()
            .get::<String>()
    );
```

works

**Comment by sdroege** [comment]
But it requires some complications for providing the actual type. If you just go from a `&str` you'd get a `s` variant. Having wrappers types for that would also seem useful or not?

**Comment by SeaDve** [comment]
> But it requires some complications for providing the actual type. If you just go from a `&str` you'd get a `s` variant. Having wrappers types for that would also seem useful or not?

Yeah, definitely, especially for `o`. I think it's impossible to construct a variant of type `o` with safe rust and without using `parse`.

**Comment by sdroege** [comment]
`g_variant_get_string()` handles all 3 types (and also the `FromVariant` impl on our side), but `g_variant_get_int32()` only handles `i` and not `h`. For `h` there's `g_variant_get_handle()`, so this sounds like using a wrapper type would be the right thing here.

There's also no e.g. `g_variant_get_object_path()` FWIW, it's all done directly via strings in C. However I think for improved type-safety we should define wrapper types around strings that enforce that the string is actually e.g. a valid object path.
