### ISSUE TITLE
glib: `ParamSpecStringBuilder::default_value()` should take `Into<Option<&str>>`

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#753]
This would allow calling it with `None`, `Some("bla")`, `"bla"`. Not so easy to do right now because of all the macro magic to generate the builders.

**Comment by bilelmoussaoui** [comment]
It would also be nice to make the Enum/Flags/Object builders take a `T: StaticType` instead of taking a `Type` parameter

**Comment by bilelmoussaoui** [comment]
Also making the default_value of enum/flags take a `impl Into<u32>` to avoid casting with `as u32` everytime

**Comment by sdroege** [comment]
> Also making the default_value of enum/flags take a `impl Into<u32>` to avoid casting with `as u32` everytime

Shouldn't it rather take a `T` instead? You'd want to provide an actual enum/flags value instead of random integers.
