### ISSUE TITLE
Bind `g_utf8` / `g_unichar` APIs

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#763]
`std` doesn't have almost anything of that, and the crate implementing all that seems is using icu, which is huge and annoying to build. The utf8 APIs should probably take `&GStr` / `GString`, otherwise we end up creating lots of copies.

**Comment by bilelmoussaoui** [comment]
Should this be closed now? cc @sdroege

**Comment by RealKC** [comment]
When binding the `g_utf8` APIs I didn't include the ones that I thought were already offered by the rust stdlib through `str` (which `GStr` gets through its `Deref<Target = &str>` impl), IIRC that was one of them.

However, the `g_unichar` APIs are still missing (some of them are offered by the stdlib already, but not all), so this issue should stay open for the time being.
