### ISSUE TITLE
`glib::Object::new()` should panic on failure and new `try_new()` variant needed

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#766]
This would be consistent with how `set_property()` and similar API work nowadays. 99% of all cases are just unwrapping on failure anyway as it's a programmer error and not a case that can be handled in a reasonable way.

**Comment by categulario** [comment]
I'll try to implement this in the next few hours...

**Comment by categulario** [comment]
Ok, so far so good. Should this change span to `gio::Initable`? or should I stop there...

**Comment by categulario** [comment]
I should've read the linked messages here... well...

**Comment by sdroege** [comment]
Sorry, I should've added a comment into this issue here. If you're looking for a similar change to work on, https://github.com/gtk-rs/gtk-rs-core/issues/773 has nobody to work on currently.

**Comment by sdroege** [comment]
Or also feel free to continue my PR. This requires further changes everywhere (and the removal of the `try` variants).
