### ISSUE TITLE
[FEATURE REQUEST] Expose fields of GDBusNodeInfo

### ISSUE THREAD

**Issue by abergmeier** [gtk-rs/gtk-rs-core#779]
In C `GDBusNodeInfo` has the following fields:
- `path`
- `interfaces`
- `nodes`
- `annotations`

These seem currently unaccessible via rust bindings.
It would be good to expose these - perhaps via functions with the same name.

**Comment by sdroege** [comment]
Do you want to provide a PR for this?

**Comment by abergmeier** [comment]
Well can you perhaps first explain what the logic/use of `DBusInterfaceExt` is?

**Comment by abergmeier** [comment]
> Do you want to provide a PR for this?

See https://github.com/gtk-rs/gtk-rs-core/pull/780

**Comment by bilelmoussaoui** [comment]
I suppose this can be closed now
