### ISSUE TITLE
Implement `Into<Value>`, `Into<Variant>`

### ISSUE THREAD

**Issue by jf2048** [gtk-rs/gtk-rs-core#788]
Or more accurately, we should have `impl From<...> for Value` and `impl From<...> for Variant` in every place where there is `ToValue` or `ToVariant`. Then we can correctly support things like `g_value_take_*`, `g_variant_new_take_string`, etc.

Then `Closure`, `BindingBuilder::transform`, `Object::new`, etc should be changed to use that instead of `ToValue`

**Comment by sdroege** [comment]
I think there was a reason to not implement that at some point but if you can make it work that would be a nice change, yes.
