### ISSUE TITLE
Use trust_return_value_nullability after making sure it doesn't cause regressions

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#789]
* [x] gdk-pixbuf ([done](https://github.com/gtk-rs/gtk-rs-core/pull/905))
* [x] gio ([done](https://github.com/gtk-rs/gtk-rs/pull/364))
* [x] glib ([done](https://github.com/gtk-rs/gtk-rs/commit/bf4198183a78a333166c4096b1843537040dd75c))
* [x] graphene
* [x] pango ([done](https://github.com/gtk-rs/gtk-rs-core/pull/797))
* [x] pangocairo ([done](https://github.com/gtk-rs/gtk-rs-core/pull/795))

CC @bilelmoussaoui @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I'll try to take a look in the next days.

**Comment by GuillaumeGomez** [comment]
For pango, we need to wait for my MRs to be merged:

 * https://gitlab.gnome.org/GNOME/pango/-/merge_requests/648
 * https://gitlab.gnome.org/GNOME/pango/-/merge_requests/647
 * https://gitlab.gnome.org/GNOME/pango/-/merge_requests/646

And for new GIR files to be generated.

**Comment by GuillaumeGomez** [comment]
And for `gdk-pixbuf` we need to wait for https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/merge_requests/146.
