### ISSUE TITLE
The trait `glib::IsA<O>` is not implemented

### ISSUE THREAD

**Issue by elmarco** [gtk-rs/gtk-rs-core#8]
The following code should work, but fails with missing IsA<O> trait implementations errors:

```rust
        impl<O: IsA<Foo>> FooExt for O {
            fn test(&self) {
                let self_ = imp::Foo::from_instance(self.downcast_ref::<Foo>());
                unimplemented!()
            }
        }
```

See related test I am about to submit.

**Comment by sdroege** [comment]
@elmarco ?

**Comment by elmarco** [comment]
The test wasn't correct. So either it was fixed, or the test was fixed. Anyway, we can close it now. Thanks
