### ISSUE TITLE
[HELP] Type has already been registered

### ISSUE THREAD

**Issue by jangernert** [gtk-rs/gtk-rs-core#825]
Sometimes when loading a listview on startup my application crashes with the following message: 

```
The application panicked (crashed).
Message:  assertion failed: `(left == right)`
  left: `94526550520048`,
 right: `0`: Type GDateTime has already been registered
Location: /home/jeanluc/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.16.3/src/subclass/boxed.rs:50
```

This seems to be some sort of race condition when a lot of the parent `ArticleGObject` are created which in turn has a property:
```
ParamSpecBoxed::new("date", "date", "date", GDateTime::static_type(), ParamFlags::READWRITE),
```

`GDateTime` is simply a box around `chrono::NaiveDateTime`

```
#[derive(Copy, Clone, Debug, PartialEq, Eq, Boxed)]
#[boxed_type(name = "GDateTime")]
pub struct GDateTime(NaiveDateTime);

impl From<NaiveDateTime> for GDateTime {
    fn from(dt: NaiveDateTime) -> Self {
        Self(dt)
    }
}

impl From<GDateTime> for NaiveDateTime {
    fn from(dt: GDateTime) -> Self {
        dt.0
    }
}
```

I'm not sure if I'm doing something wrong here or if there is a bug in the bindings.

What I'm trying right now is to register all the subtypes on class_init. But since I hit the crash only every few weeks/monts I have no idea if that helps.

```
    #[glib::object_subclass]
    impl ObjectSubclass for ArticleGObject {
        const NAME: &'static str = "ArticleGObject";
        type Type = super::ArticleGObject;
        type ParentType = glib::Object;

        fn class_init(_klass: &mut Self::Class) {
            GDateTime::ensure_type();
            GRead::ensure_type();
            GMarked::ensure_type();
            GTags::ensure_type();
        }
    }
```

**Comment by sdroege** [comment]
You need to namespace your `GType` name strings properly. There already is a `GDateTime` inside GLib (`glib::DateTime`) and you registering another type with that name fails.

The name strings are a flat namespace so you probably want to use something like `YourApplicationDateTime` or so :)

**Comment by jangernert** [comment]
@sdroege ah, thank you very much. I didn't think about that at all. Do you by any chance have an explanation for the randomness of the issue? If not, just ignore the question ;)

**Comment by sdroege** [comment]
It will succeed if nothing uses a `glib::DateTime` in a way that registers the `GType` of it. That's the only explanation I would have. Is that possible in your code?

**Comment by jangernert** [comment]
I don't think so. At least directly there should be no use of `glib::DateTime`. The crash happens sometimes when logging into an account and the list of articles is shown for the first time.

Anyway, I'll change the name of my types and consider this bug as fixed until it happens again :)
