### ISSUE TITLE
`ParamSpecEnumBuilder` should take `Default::default()` into consideration

### ISSUE THREAD

**Issue by pbor** [gtk-rs/gtk-rs-core#831]
**Description**

`ParamSpecEnumBuilder` today does not expose a `.default_value` setter. When asking on the chat, I think that today it is just `0` by default.

We should:
1. document the behavior
2. Since enums can implement the `Default` trait, we should honor it

**Comment by sdroege** [comment]
> When asking on the chat, I think that today it is just `0` by default.

It requires passing the default value, always.

I think we should have

```rust
pub fn builder()<T: StaticType + FromGlib<i32> + IntoGlib<GlibType = i32> + Default>(
    name: &str,
) -> ParamSpecEnumBuilder<'_, T>;
pub fn builder()_with_default<T: StaticType + FromGlib<i32> + IntoGlib<GlibType = i32>>(
    name: &str,
    default_value: T,
) -> ParamSpecEnumBuilder<'_, T>
```

What do you think?

**Comment by bilelmoussaoui** [comment]
I would leave the current constructor as is and add a `with_default` variant that would require `T: Default`

**Comment by sdroege** [comment]
@bilelmoussaoui I also don't want to change the API, but a `with_default()` sounds like it as a default parameter :) Do you have another name suggestion?

**Comment by pbor** [comment]
I do not think the API break is a problem as long it is something that the compiler can catch. The important thing is that we do not keep the same signature and change the behavior.

**Comment by sdroege** [comment]
Well that's not possible here anyway (to keep the same signature but change the behaviour) :)
