### ISSUE TITLE
[FEATURE REQUEST] both gdk_pixbuf::{PixbufAnimation,PixbufAnimationIter} are missing a IsSubclassable trait implementation

### ISSUE THREAD

**Issue by aruiz** [gtk-rs/gtk-rs-core#834]
To write a Gdk Pixbuf loader with animation support in Rust one needs to subclass GdkPixbufAnimation and GdkPixbufAnimationIter. Without the IsSubclassavble trait implementation this is not possible.

**Comment by sdroege** [comment]
Exciting :partying_face:

**Comment by sdroege** [comment]
@aruiz Do you want this backported to the 0.16 release?

**Comment by aruiz** [comment]
Wow, that was fast! @bilelmoussaoui thanks for working on this!

If you can backport it that'd be great. In the meantime I'll use the git path in cargo.

Thank you too @sdroege

**Comment by sdroege** [comment]
Already backported and will be in the next 0.16 bugfix release, probably tomorrow

**Comment by aruiz** [comment]
Awesome, thanks @sdroege!!!!
