### ISSUE TITLE
glib::Receiver panicks when attaching to MainContext

### ISSUE THREAD

**Issue by Ryuukyu313** [gtk-rs/gtk-rs-core#88]
Since a few days, I cannot attach a `glib::Receiver` to the `MainContext` anymore.

Minified example (using gtk4):
```rust
use glib::{prelude::Continue, PRIORITY_DEFAULT};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    gtk4::init()?;

    let (_sender, receiver) = glib::MainContext::channel::<()>(PRIORITY_DEFAULT);
    receiver.attach(None, |_| Continue(true));

    Ok(())
}
```

This panics with this message:
```
thread 'main' panicked at 'assertion failed: context.is_owner()', /home/tomwagner/.cargo/git/checkouts/gtk-rs-core-7be42ca38bd6361c/aca50f8/glib/src/main_context_channel.rs:507:17
```

Above code run with `RUST_BACKTRACE=full`:
[backtrace.txt](https://github.com/gtk-rs/gtk-rs-core/files/6524596/backtrace.txt)

I am running Fedora 34, rustc 1.52.1, glib 1.2.10, gtk-rs from master.

The same code compiled with an older Cargo.lock using https://github.com/gtk-rs/gtk-rs-core/commit/74a02cdd2855a387ebbe700eb509029c8e338d19 still runs fine.

**Comment by bilelmoussaoui** [comment]
Cargo update should fix it

**Comment by sdroege** [comment]
That worked before because `gtk4::init()` was "leaking" the main context. You'd have to make sure to acquire the main context in your main thread before using the main context channel, i.e.

```rust
let ctx = glib::MainContext::default();
let _guard = ctx.acquire().unwrap();
[... all your code ...]
```

See also https://gtk-rs.org/gtk-rs-core/git/docs/glib/struct.Receiver.html#panics

**Comment by Ryuukyu313** [comment]
Thanks, my code works again!
