### ISSUE TITLE
[BUG] boxed types do not implement the `ToGlibPtr` for `*const` pointers

### ISSUE THREAD

**Issue by mbiggio** [gtk-rs/gtk-rs-core#889]
**Bug description**

It looks like boxed types do not implement the `ToGlibPtr` to convert from the wrapped object to the `*const` pointer.

Seems that [only the `*mut`](https://github.com/gtk-rs/gtk-rs-core/blob/master/glib/src/boxed.rs#L78) implementation is present.
Is there any specific reason for that?
Thanks!

**Comment by sdroege** [comment]
Boxed types usually have correct const'ness in C APIs, but you're right that this should be added for completeness. Do you want to submit a PR?

**Comment by mbiggio** [comment]
Sure, I can do that :)
