### ISSUE TITLE
[BUG] PixbufAnimationImplExt::animation_get_size

### ISSUE THREAD

**Issue by aruiz** [gtk-rs/gtk-rs-core#927]
animation_get_size in pixbuf_animation.rs sets values to pointers like this:
```
unsafe extern "C" fn animation_get_size<T: PixbufAnimationImpl>(
    ptr: *mut ffi::GdkPixbufAnimation,
    width_ptr: *mut libc::c_int,
    height_ptr: *mut libc::c_int,
) {
    let instance = &*(ptr as *mut T::Instance);
    let imp = instance.imp();

    let (width, height) = imp.size();
    *width_ptr = width;
    *height_ptr = height;
}
```

However width_ptr/height_ptr are nullable so that you can request width or height independently.

**Comment by aruiz** [comment]
I have crated a PR to fix this https://github.com/gtk-rs/gtk-rs-core/pull/928

**Comment by aruiz** [comment]
Any chance to get this backported to 0.16?

**Comment by sdroege** [comment]
Yes, can do that in the next days. Do you need any other changes too?

**Comment by aruiz** [comment]
Just this one, thank you!
