### ISSUE TITLE
properties: Remove flags special handling and use builder

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#929]
```rust
// before
#[property(..., explicit_notify, builder()...]
// after
#[property(..., builder().explicit_notify()...]
```

This would allow GStreamer to use `mutable_ready()` instead of the very long `gst::PARAM_FLAGS_MUTABLE_READY` and also seems overall more consistent.

Currently when using the flags parts of the builder it will compile fine but that flags are simply overwritten completely.

CC @ranfdev @bilelmoussaoui

**Comment by sdroege** [comment]
Conclusion from the matrix discussion seems to be to do exactly that: remove the flags special handling for now.

**Comment by ranfdev** [comment]
Well, we should remove support for `#[get, glib::Flags::EXPLICIT_NOTIFY]`,
but we should keep support for `#[get, explicit_notify]`, because the basic flags included in glib cover 99% of the use cases.
At least, that's what I concluded from the chat.

The macro must be changed to add the flag without overwriting the previous ones set in the builder expression. That's possible by letting the macro create an expression similar to `builder().flag_from_the_builder_expr(). explicit_notify()`

**Comment by sdroege** [comment]
Works for me

**Comment by sdroege** [comment]
As suggested on Matrix earlier:

> I was wondering for the properties macro, why don't we translate all "unknown" arguments of it after get/set to calls to the builder? so
>
> ```
> 123#[property(get, set, builder(), nick("bla"), explicit_notify, bla("123", 123)]
> ```
> becomes
> ```
> builder().nick("bla").explicit_notify().bla("123", 123).build()
> ```
>
> In the front you'd have the special arguments that the macro requires for working, then at some point the builder(...) call, then afterwards are just arguments to that. that way none of the flags need to be handled specially (neither do nick, name, description) and there is not a single potentially long chain of function calls in there

That should simplify things generally unless I'm missing something? Maybe we could also rename `builder(...)` to something else that looks less strange in this context. Not sure what though.

**Comment by A6GibKm** [comment]
That would work very nicely, but I am guessing on could just remove the need to write builder()

**Comment by bilelmoussaoui** [comment]
right, we could just pass every "unknown" attributes to the builder, so you could write `#[property(get, set, nick = "something", minimum=12)]`

**Comment by ranfdev** [comment]
I guess this can be closed

**Comment by bilelmoussaoui** [comment]
Right, thanks!
