### ISSUE TITLE
properties: Can't use the macro for a custom glib::Boxed type property

### ISSUE THREAD

**Issue by melix99** [gtk-rs/gtk-rs-core#932]
This is a minimal reproducer of what I'm trying to do: [lib.zip](https://github.com/gtk-rs/gtk-rs-core/files/10538714/lib.zip).

The compilation fails with:

```
error[E0277]: the trait bound `RefCell<Option<StrBoxed>>: Property` is not satisfied
  --> src/lib.rs:16:21
   |
16 |     #[derive(Debug, Properties, Default)]
   |                     ^^^^^^^^^^ the trait `Property` is not implemented for `RefCell<Option<StrBoxed>>`
   |
   = help: the trait `Property` is implemented for `RefCell<T>`
   = note: this error originates in the derive macro `Properties` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
```

Am I just doing something wrong?

**Comment by bilelmoussaoui** [comment]
We are probably missing a HasParamSpec trait impl, could you try adding a manual implementation to your type and see if it helps?

**Comment by melix99** [comment]
@bilelmoussaoui That gives me:

```
error[E0119]: conflicting implementations of trait `glib::HasParamSpec` for type `StrBoxed`
 --> src/lib.rs:4:17
  |
4 | #[derive(Clone, glib::Boxed)]
  |                 ^^^^^^^^^^^ conflicting implementation for `StrBoxed`
...
8 | impl glib::HasParamSpec for StrBoxed {
  | ------------------------------------ first implementation here
  |
  = note: this error originates in the derive macro `glib::Boxed` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by sdroege** [comment]
I think what we're missing is the `Option<T>` part here, not `StrBoxed`. That would need a generic impl in `glib`

**Comment by bilelmoussaoui** [comment]
> I think what we're missing is the `Option<T>` part here, not `StrBoxed`. That would need a generic impl in `glib`

Isn't it expected that `ParamSpecBoxed` doesn't accept nullable values? as in, I would expect the user to have `StrBoxed(Option<Str>)`  instead

**Comment by sdroege** [comment]
Most boxed/object properties are nullable, and you can derive boxed/shared as nullable too.

**Comment by ranfdev** [comment]
`HasParamSpec` is implemented on every type `Option<T>` where `T: glib::value::ToValueOptional`.

If `StrBoxed` doesn't implement `ToValueOptional`, the macro can't handle it. `Option<StrBoxed>` can't be converted to a glib value at all, so it can't be treated as a property.

Workarounds without implementing `ToValueOptional`:
- Adding `type = StrBoxed` and manually adding a getter and a setter.
- Using [glib::ConstructCell](https://gtk-rs.org/gtk-rs-core/git/docs/glib/struct.ConstructCell.html#), if you plan on setting the value during construction, and then keeping it always `Some(x)`. This type didn't get much love/testing yet.

**Comment by sdroege** [comment]
`StrBoxed` would have to use 

```rust
#[derive(Clone, Debug, PartialEq, Eq, glib::Boxed)]
#[boxed_type(name = "MyStrBoxed", nullable)]
pub struct StrBoxed { ... }
```

**Comment by melix99** [comment]
> Most boxed/object properties are nullable, and you can derive boxed/shared as nullable too.

Oh, yeah, you're right, I completely forgot about deriving nullable. Now it works, thanks :)

> Using [glib::ConstructRefCell](https://gtk-rs.org/gtk-rs-core/git/docs/glib/struct.ConstructRefCell.html#), if you plan on setting the value during construction, and then keeping it always Some(x). This type didn't get much love/testing yet.

That's super nice, I'll definitely try it soon in my projects :)

I'll consider this solved then.
