### ISSUE TITLE
GFile: enumerate_children_future requires static borrow

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk-rs-core#942]
The properties need a static borrow which is a bit annoying. It's possible to create a static for that, but maybe just allowing something like a `String` directly would make sense?

https://gtk-rs.org/gtk-rs-core/git/docs/gio/prelude/trait.FileExtManual.html#tymethod.enumerate_children_future

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/944
