### ISSUE TITLE
glib: Consider changing `GStrPtr`

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs-core#949]
@jf2048 wrote on Matrix

![image](https://user-images.githubusercontent.com/301846/216757409-d4b1531d-76fe-4a75-8d78-a8a306ed3aae.png)

CC @pbor 

(ridiculous that you can't copy&paste text properly from matrix)

**Comment by pbor** [comment]
I agree on the rename to `GStringPtr`... do we really need `GStrPtr` as well right now? I do not `const char **` is very common in API.

I am also ok with dropping `AsRef` an `Deref`.

I am not sure I understand the suggestion about `StrVBorrowed`

**Comment by sdroege** [comment]
> do we really need `GStrPtr` as well right now? I do not `const char **` is very common in API.

I don't think that's needed, yes.

**Comment by pbor** [comment]
https://github.com/gtk-rs/gtk-rs-core/pull/950 is the simple rename

Thinking more about it I do not think we should change from `as_str` to `to_str` because the guidelines say that it is for expensive conversions, which is true for `CStr` since it needs to check utf-8, but it is not true here.

**Comment by pbor** [comment]
After some more coffee I realized that the conversion requires walking the string to find the length, so it is expensive.

I added a second commit the the PR to remove all the `AsRef` implementations and use `to_gstr` explicitely

**Comment by jf2048** [comment]
There are a couple that return `const char **`:

- https://docs.gtk.org/gio/method.AppInfo.get_supported_types.html
- https://docs.gtk.org/glib/method.Variant.get_strv.html

For those there could just be a separate borrowed type.
