### ISSUE TITLE
[BUG] `glib::ValueArray` should impl `HasParamSpec<ParamSpec = ParamSpecValueArray>>` not `ParamSpecBoxed`

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk-rs-core#971]
It's a Boxed type, so the `wrapper!` macro auto implements ParamSpecBoxed, but it should be `ParamSpecValueArray`.

There's currently no way to define a property using `ParamSpecValueArray` (unless the user declares a custom wrapper type and implements `HasParamSpec` by themself)

**Comment by sdroege** [comment]
Yeah, needs a manual implementation for all the value traits then.
