### ISSUE TITLE
Drop Default impl from ListStore

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs-core#975]
Maybe just rename the constructor to something else to avoid foot guns with `#[derive(Default)]`

**Comment by sdroege** [comment]
There's no problem with the `new()` function because it takes a parameter. That can stay as it is :)

**Comment by bilelmoussaoui** [comment]
> There's no problem with the `new()` function because it takes a parameter. That can stay as it is :)

Yes, I meant replacing `ListStore::default()` with something like `ListStore::default_object()`

**Comment by sdroege** [comment]
I would just remove that one. What is it good for?

**Comment by pbor** [comment]
The `Default` is generated because gir generates one every time `generate_builder` is true. We need a new flag in gir or better heuristic
