### ISSUE TITLE
[FEATURE REQUEST] Add more implementations of `IntoStrV`, `IntoOptionalGStr` etc

### ISSUE THREAD

**Issue by andy128k** [gtk-rs/gtk-rs-core#976]
Currently `IntoStrV` is not implemented for `[&str; N]` and a cast to a slice is needed.

`IntoOptionalGStr` could also be implemented for string types, similar to how `impl Into<Option<&str>>` accepts string literals.

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk-rs-core/pull/977
