### ISSUE TITLE
[FEATURE REQUEST] Make `glib::WeakRef` useable with the `Properties` derive macro

### ISSUE THREAD

**Issue by RealKC** [gtk-rs/gtk-rs-core#980]
Currently it's missing some trait impls

**Comment by sdroege** [comment]
That should theoretically be easy to add. It should only require the trait impls of `RefCell`, plus the `T` should be constrained to `IsA<Object>`.

Do you want to give it a try?

**Comment by RealKC** [comment]
Yeah sure
