### ISSUE TITLE
[BUG] properties: setter (on wrapper type) for a `RefCell<Option<Obj>>` takes `Borrow<Obj>` instead of `Borrow<Option<Obj>>`

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk-rs-core#990]
Using `Borrow` in the setter was a trick to let `String` properties have a setter taking `Borrow<str>` and  `Object` properties having a setter taking any `Borrow<$Subclass>`.

But once the type is wrapped inside an `Option`, everything breaks. `Borrow` isn't recursive.
```
328 |         myfoo.set_object(Some(glib::BoxedAnyObject::new("")));
    |               ---------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Borrow<Option<Object>>` is not implemented for `Option<BoxedAnyObject>`
    |               |
    |               required by a bound introduced by this call
```

I currently don't know how to solve this.

**Comment by jf2048** [comment]
To fix the casting for real, we would need another trait `IntoWithCast` or something, that we need to manually implement for every `HasParamSpec` type
