### ISSUE TITLE
[FEATURE REQUEST] properties macro: automatically prepend `is_` on generated getter functions on bool properties

### ISSUE THREAD

**Issue by SeaDve** [gtk-rs/gtk-rs-core#993]
I believe it makes it more consistent with the generated bindings and it sounds more natural.

Example:
```rust
mod imp {
    #[derive(glib::Properties, Default)]
    #[properties(wrapper_type = super::Item)]
    pub struct Item {
        #[property(get, set)]
        pub(super) new: Cell<bool>,
    }

    ...
}

...
```

should have a generated getter of `obj.is_new()` instead of just `obj.new()`.

**Comment by sdroege** [comment]
Why don't you name you property `is-new` then? As you say, that sounds much more natural :)

**Comment by SeaDve** [comment]
I keep it consistent with how the bindings handle bool properties like [sensitive](https://gtk-rs.org/gtk4-rs/git/docs/gtk4/prelude/trait.WidgetExt.html#tymethod.is_sensitive) and [visible](https://gtk-rs.org/gtk4-rs/git/docs/gtk4/prelude/trait.WidgetExt.html#tymethod.is_visible), where the property does not have `is-` prefix, but the getter function has. Not a big deal, but maybe something to consider

**Comment by bilelmoussaoui** [comment]
> I keep it consistent with how the bindings handle bool properties like [sensitive](https://gtk-rs.org/gtk4-rs/git/docs/gtk4/prelude/trait.WidgetExt.html#tymethod.is_sensitive) and [visible](https://gtk-rs.org/gtk4-rs/git/docs/gtk4/prelude/trait.WidgetExt.html#tymethod.is_visible), where the property name does not have `is-` prefix, but the getter function do. Not a big deal, but maybe something to consider.

Right, except those are part of the C API that is being adapted to Rust

**Comment by sdroege** [comment]
There's also a lot of C API that prefixes the property names. `is-` `has-` etc.

**Comment by SeaDve** [comment]
I guess it is not worth it then to make the macro more complex just for this, I think I'll close this

**Comment by yuraiz** [comment]
Or it's possible to use `is` or `has` keywords instead of `get`

**Comment by bilelmoussaoui** [comment]
> Or it's possible to use `is` or `has` keywords instead of `get`

No. Please name your properties as wish them to be named. Regarding naming your property as loop, see https://github.com/gtk-rs/gtk-rs-core/issues/1067

**Comment by yuraiz** [comment]
But I want setter to have normal name `set_loop`

**Comment by yuraiz** [comment]
`is` prefix is used for many places in standart library: https://doc.rust-lang.org/std/?search=is_
